import { Plan, Destination, Testimonial, AboutUsContent, LegalContent, FAQItem } from './types';

export const DEFAULT_LOGO_URL = 'https://lh3.googleusercontent.com/pw/AP1GczMVaa2t54xizfCT4x_LuthxbgVvbVait9QQs24AIFmmP11LvYGDQCc64rLNBOLySyjTMcywDRVWC5dm5Qlh5NNm9pOTJYkVQXX9XOHUlLIpOHbE4-5gZOdIICB1sueb_fejAJa5mRmHv-1PNAbqA-U=w991-h991-s-no-gm?authuser=0';
export const DEFAULT_PLANIBOT_AVATAR_URL = 'https://lh3.googleusercontent.com/pw/AP1GczN-20Rl_25uHFSXkszlbrLCBXowweXMKM6gxTaAT5SxEiJzHe6w1RzNl3uS9CDqypFK2VJwzZ0FJTKL2B9BsZwJg4yYjms8Xs6DGU6GvzMZ842bWpb6K9sot2XwqJdManGzs9soffeOFZjMlRm6COE=w991-h991-s-no-gm?authuser=0';
export const DEFAULT_SEO_IMAGE_URL = 'https://lh3.googleusercontent.com/pw/AP1GczNUIa2Fy-Hhas1rZIB4R6Mj0mFRmPDohbP1jYOdZnKtBVNxvp55GGLoti6L45527kFqs5qmxVBLk19-42n2WG70HqrA97KhoOwO-WMxBKEfGXtvdjc5Qo4n9yno1pj5BwZAOb7ZkPpqc0hPRs3vEC0=w991-h991-s-no-gm?authuser=0';


export const DEFAULT_CONTACT_INFO = {
  phone: "+57 3113653379",
  whatsappLink: "https://wa.me/573113653379",
  email: "planificatusueno12@gmail.com",
  address: "Centro comercial La Colmena, Cra. 4 #13-32, Anserma, Caldas",
  schedule: "Lun-Vie: 8am-12pm y 2pm-5:30pm; Sáb: 8am-1pm",
  rnt: "181495",
};

export const DEFAULT_SOCIAL_LINKS = {
  facebook: "https://www.facebook.com/planifica.tusueno/",
  instagram: "https://www.instagram.com/planificatusueno/",
  tiktok: "https://www.tiktok.com/@planificatusueno",
};

export const DEFAULT_TRAVEL_PLANS: Plan[] = [
  {
    id: 1,
    title: "Finca Hotel San Isidro",
    category: "Rural",
    price: "Consultar Precio",
    priceValue: 350000,
    durationDays: 2,
    description: "Un paraíso rural para el descanso. Disfruta de habitaciones confortables, piscina, jacuzzi, turco, senderos ecológicos y cascadas naturales. Una experiencia de desconexión total con todas las comodidades. No se admiten mascotas.",
    images: ["https://picsum.photos/seed/finca-san-isidro-1/800/600", "https://picsum.photos/seed/finca-san-isidro-2/800/600", "https://picsum.photos/seed/finca-san-isidro-3/800/600"],
    includes: ["Alojamiento", "Alimentación (cena, desayuno, almuerzo)", "Seguro de accidentes", "Acceso a piscina, jacuzzi y turco", "Senderos ecológicos"],
    isVisible: true,
    departureDate: "2024-11-10",
    returnDate: "2024-11-12",
    country: "Colombia",
    city: "Eje Cafetero",
    regime: "Pensión Completa",
    travelerTypes: ["Descanso / Relax", "Familias", "Parejas"],
    amenities: ["Wifi Gratis", "Piscina", "Jacuzzi", "Turco / Baño de vapor", "Restaurante"],
  },
  {
    id: 2,
    title: "Hotel Sansiraka",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 450000,
    durationDays: 3,
    description: "Propiedad de estilo colonial con amplios jardines en Santa Marta, cerca de El Rodadero. Ofrece una piscina al aire libre, jacuzzi, baño de vapor, restaurante, bar con karaoke y espectáculos nocturnos.",
    images: ["https://picsum.photos/seed/sansiraka-1/800/600", "https://picsum.photos/seed/sansiraka-2/800/600", "https://picsum.photos/seed/sansiraka-3/800/600"],
    includes: ["Alojamiento con aire acondicionado", "Acceso a zonas húmedas", "Internet inalámbrico", "Centro de negocios"],
    isVisible: true,
    departureDate: "2024-12-10",
    returnDate: "2024-12-13",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Familias", "Grupos"],
    amenities: ["Piscina", "Jacuzzi", "Turco / Baño de vapor", "Bar / Lounge", "Restaurante", "Shows Nocturnos / Animación", "Centro de Negocios", "Wifi Gratis", "Estacionamiento", "Aire Acondicionado", "Balcón / Terraza"],
  },
  {
    id: 3,
    title: "Hotel GHL Costa Azul",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 550000,
    durationDays: 3,
    description: "Hotel de playa en la zona residencial de Pozos Colorados, Santa Marta. Ideal para familias, con piscina, piscina para niños, jacuzzi, sauna y restaurante de platos típicos.",
    images: ["https://picsum.photos/seed/ghl-costa-azul-1/800/600", "https://picsum.photos/seed/ghl-costa-azul-2/800/600", "https://picsum.photos/seed/ghl-costa-azul-3/800/600"],
    includes: ["Alojamiento en habitación con balcón", "Acceso a piscina, piscina para niños, jacuzzi y sauna", "Internet inalámbrico gratuito", "Bar en la piscina"],
    isVisible: true,
    departureDate: "2025-01-15",
    returnDate: "2025-01-18",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Descanso / Relax"],
    amenities: ["Piscina", "Piscina para niños", "Jacuzzi", "Sauna", "Acceso a la Playa", "Wifi Gratis", "Aire Acondicionado", "Balcón / Terraza", "Vista al Mar", "Bar / Lounge", "Mesa de Tours"],
  },
  {
    id: 4,
    title: "Grand Decameron Panamá",
    category: "Internacional",
    price: "Consultar Precio",
    priceValue: 3200000,
    durationDays: 5,
    description: "Complejo todo incluido en Playa Blanca, Farallón. Ofrece una amplia oferta recreativa con 11 piscinas, toboganes, campo de golf de 18 hoyos, spa, 8 restaurantes y club nocturno.",
    images: ["https://picsum.photos/seed/decameron-panama-1/800/600", "https://picsum.photos/seed/decameron-panama-2/800/600", "https://picsum.photos/seed/decameron-panama-3/800/600"],
    includes: ["Alojamiento todo incluido", "Comidas y bebidas ilimitadas", "Deportes acuáticos no motorizados", "Entretenimiento nocturno", "Acceso a 11 piscinas y toboganes"],
    isVisible: true,
    departureDate: "2025-02-10",
    returnDate: "2025-02-15",
    country: "Panamá",
    city: "Playa Blanca",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Grupos", "Parejas"],
    amenities: ["Piscina", "Toboganes / Parque Acuático", "Campo de Golf", "Spa", "Shows Nocturnos / Animación", "Restaurante", "Bar / Lounge", "Discoteca / Club Nocturno", "Acceso a la Playa", "Aire Acondicionado", "Balcón / Terraza", "Cocineta", "Salón de Eventos / Conferencias", "Mesa de Tours"],
  },
  {
    id: 5,
    title: "Hotel Marina Suites",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 480000,
    durationDays: 3,
    description: "Ubicación ideal en el moderno sector de Bocagrande en Cartagena, a 2 cuadras del mar. Ofrece desayuno americano, internet inalámbrico y centro de negocios.",
    images: ["https://picsum.photos/seed/marina-suites-1/800/600", "https://picsum.photos/seed/marina-suites-2/800/600", "https://picsum.photos/seed/marina-suites-3/800/600"],
    includes: ["Alojamiento con aire acondicionado", "Desayuno estilo americano", "Internet inalámbrico gratuito", "Centro de negocios"],
    isVisible: true,
    departureDate: "2024-11-20",
    returnDate: "2024-11-23",
    country: "Colombia",
    city: "Cartagena",
    regime: "Con Desayuno Incluido",
    travelerTypes: ["Parejas", "Negocios"],
    amenities: ["Cerca de la Playa", "Wifi Gratis", "Aire Acondicionado", "Estacionamiento", "Centro de Negocios", "Mesa de Tours"],
  },
  {
    id: 6,
    title: "Grand Bávaro Princess All Suites Resort",
    category: "Internacional",
    price: "Consultar Precio",
    priceValue: 4100000,
    durationDays: 6,
    description: "Hotel todo incluido en Punta Cana. Disfruta de una gran variedad de actividades deportivas, club de niños, gimnasio, dos piscinas, jacuzzi, sauna y spa.",
    images: ["https://picsum.photos/seed/bavaro-princess-1/800/600", "https://picsum.photos/seed/bavaro-princess-2/800/600", "https://picsum.photos/seed/bavaro-princess-3/800/600"],
    includes: ["Alojamiento todo incluido", "Deportes acuáticos", "Clases de baile", "Club de niños", "Acceso a piscinas y zonas húmedas"],
    isVisible: true,
    departureDate: "2025-03-05",
    returnDate: "2025-03-11",
    country: "República Dominicana",
    city: "Punta Cana",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Parejas", "Grupos"],
    amenities: ["Piscina", "Jacuzzi", "Sauna", "Spa", "Gimnasio", "Club de niños", "Acceso a la Playa", "Deportes Acuáticos", "Shows Nocturnos / Animación", "Restaurante", "Bar / Lounge", "Salón de Eventos / Conferencias", "Casino", "Balcón / Terraza", "Minibar / Refrigerador"],
  },
  {
    id: 7,
    title: "Hotel Imperial Las Perlas",
    category: "Internacional",
    price: "Consultar Precio",
    priceValue: 2900000,
    durationDays: 5,
    description: "Hotel familiar todo incluido en Cancún con magníficas vistas al Mar Caribe. Ideal para disfrutar de la playa, deportes acuáticos y un ambiente relajado.",
    images: ["https://picsum.photos/seed/imperial-perlas-1/800/600", "https://picsum.photos/seed/imperial-perlas-2/800/600", "https://picsum.photos/seed/imperial-perlas-3/800/600"],
    includes: ["Alojamiento todo incluido", "Comidas y bebidas", "Deportes acuáticos como piragua", "Conexión Wi-Fi"],
    isVisible: true,
    departureDate: "2025-01-20",
    returnDate: "2025-01-25",
    country: "México",
    city: "Cancún",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Acceso a la Playa", "Deportes Acuáticos", "Wifi Gratis", "Restaurante", "Bar / Lounge"],
  },
  {
    id: 8,
    title: "Hotel Azuan Suites",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 420000,
    durationDays: 3,
    description: "Ubicado en el moderno barrio de Bocagrande, Cartagena. Ofrece wifi gratis, aire acondicionado y está a solo 4 cuadras de la playa.",
    images: ["https://picsum.photos/seed/azuan-suites-1/800/600", "https://picsum.photos/seed/azuan-suites-2/800/600", "https://picsum.photos/seed/azuan-suites-3/800/600"],
    includes: ["Alojamiento con aire acondicionado", "Wifi gratis", "Servicio de despertador", "Información turística"],
    isVisible: true,
    departureDate: "2024-11-25",
    returnDate: "2024-11-28",
    country: "Colombia",
    city: "Cartagena",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Negocios"],
    amenities: ["Cerca de la Playa", "Wifi Gratis", "Aire Acondicionado"],
  },
  {
    id: 9,
    title: "Hotel Lord Pierre",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 750000,
    durationDays: 4,
    description: "Una propiedad en San Andrés que cuenta con piscina y muelle con solárium. Tiene un área de playa y ofrece tours para actividades acuáticas. Posee dos restaurantes y un bar sobre el muelle.",
    images: ["https://picsum.photos/seed/lord-pierre-1/800/600", "https://picsum.photos/seed/lord-pierre-2/800/600", "https://picsum.photos/seed/lord-pierre-3/800/600"],
    includes: ["Alojamiento", "Acceso a piscina y muelle", "Mesa de tours"],
    isVisible: true,
    departureDate: "2025-02-01",
    returnDate: "2025-02-05",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Grupos"],
    amenities: ["Piscina", "Acceso a la Playa", "Restaurante", "Bar / Lounge", "Mesa de Tours"],
  },
  {
    id: 10,
    title: "Hotel On Vacation Caribbean",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 680000,
    durationDays: 4,
    description: "Hotel libre de humo cerca de la playa en San Andrés. Ofrece 66 habitaciones con aire acondicionado, restaurante y resguardo de equipaje.",
    images: ["https://picsum.photos/seed/on-vacation-caribbean-1/800/600", "https://picsum.photos/seed/on-vacation-caribbean-2/800/600", "https://picsum.photos/seed/on-vacation-caribbean-3/800/600"],
    includes: ["Alojamiento con aire acondicionado", "Servicio de internet", "Restaurante"],
    isVisible: true,
    departureDate: "2025-01-10",
    returnDate: "2025-01-14",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Grupos", "Familias"],
    amenities: ["Cerca de la Playa", "Aire Acondicionado", "Wifi Gratis", "Restaurante"],
  },
  {
    id: 11,
    title: "Hotel On Vacation Amazon",
    category: "Aventura",
    price: "Consultar Precio",
    priceValue: 950000,
    durationDays: 4,
    description: "Ubicado a las afueras de Leticia, en una zona a la que sólo se puede llegar en bote. Rodeado de selva, este hotel ofrece una experiencia única con piscina y restaurante. Nota: las habitaciones ofrecen únicamente agua fría.",
    images: ["https://picsum.photos/seed/on-vacation-amazon-1/800/600", "https://picsum.photos/seed/on-vacation-amazon-2/800/600", "https://picsum.photos/seed/on-vacation-amazon-3/800/600"],
    includes: ["Alojamiento con vista a la selva", "Desayuno, almuerzo y cena", "Acceso a la piscina"],
    isVisible: true,
    departureDate: "2025-04-01",
    returnDate: "2025-04-05",
    country: "Colombia",
    city: "Leticia",
    regime: "Pensión Completa",
    travelerTypes: ["Grupos", "Aventura"],
    amenities: ["Piscina", "Restaurante", "Bar / Lounge", "Aire Acondicionado"],
  },
  {
    id: 12,
    title: "Hotel Tamacá Beach Resort",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 620000,
    durationDays: 3,
    description: "Ubicado frente al mar en El Rodadero, Santa Marta. Cuenta con piscina con vista al mar, acceso a la playa, jacuzzi, centro de negocios y restaurante de especialidades.",
    images: ["https://picsum.photos/seed/tamaca-beach-1/800/600", "https://picsum.photos/seed/tamaca-beach-2/800/600", "https://picsum.photos/seed/tamaca-beach-3/800/600"],
    includes: ["Alojamiento con vista al mar", "Acceso a piscina y jacuzzi", "Internet inalámbrico", "Centro de negocios"],
    isVisible: true,
    departureDate: "2025-02-15",
    returnDate: "2025-02-18",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Familias", "Negocios"],
    amenities: ["Piscina", "Jacuzzi", "Acceso a la Playa", "Wifi Gratis", "Aire Acondicionado", "Centro de Negocios", "Restaurante", "Bar / Lounge", "Salón de Eventos / Conferencias", "Vista al Mar", "Minibar / Refrigerador"],
  },
  {
    id: 13,
    title: "Hotel Whala!bávaro",
    category: "Internacional",
    price: "Consultar Precio",
    priceValue: 3500000,
    durationDays: 5,
    description: "Hotel todo incluido cerca de la playa en Bávaro, Punta Cana. Cuenta con tres piscinas, dos restaurantes, dos bares, gimnasio, club infantil y un programa completo de actividades.",
    images: ["https://picsum.photos/seed/whala-bavaro-1/800/600", "https://picsum.photos/seed/whala-bavaro-2/800/600", "https://picsum.photos/seed/whala-bavaro-3/800/600"],
    includes: ["Alojamiento todo incluido", "Comidas y bebidas", "Acceso a piscinas", "Gimnasio", "Club infantil", "Programa de animación"],
    isVisible: true,
    departureDate: "2025-03-20",
    returnDate: "2025-03-25",
    country: "República Dominicana",
    city: "Punta Cana",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Piscina", "Cerca de la Playa", "Gimnasio", "Club de niños", "Shows Nocturnos / Animación", "Restaurante", "Bar / Lounge", "Wifi Gratis", "Aire Acondicionado", "Balcón / Terraza", "Minibar / Refrigerador"],
  },
  {
    id: 14,
    title: "Hotel Cartagena Plaza",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 780000,
    durationDays: 4,
    description: "Ubicación privilegiada frente al mar en Cartagena. Piscina en el piso 18 con vistas panorámicas, club nocturno, club de niños, centro de negocios y dos restaurantes.",
    images: ["https://picsum.photos/seed/cartagena-plaza-1/800/600", "https://picsum.photos/seed/cartagena-plaza-2/800/600", "https://picsum.photos/seed/cartagena-plaza-3/800/600"],
    includes: ["Alojamiento con vista al mar", "Acceso a piscina panorámica", "Club de niños", "Club nocturno", "Internet inalámbrico"],
    isVisible: true,
    departureDate: "2025-04-10",
    returnDate: "2025-04-14",
    country: "Colombia",
    city: "Cartagena",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Parejas", "Grupos"],
    amenities: ["Piscina", "Acceso a la Playa", "Shows Nocturnos / Animación", "Discoteca / Club Nocturno", "Club de niños", "Wifi Gratis", "Aire Acondicionado", "Restaurante", "Bar / Lounge", "Centro de Negocios", "Salón de Eventos / Conferencias", "Hotel accesible", "Vista al Mar"],
  },
  {
    id: 15,
    title: "Hotel Playa Blanca Beach Resort",
    category: "Internacional",
    price: "Consultar Precio",
    priceValue: 3300000,
    durationDays: 4,
    description: "Hotel familiar todo incluido en Playa Blanca, Panamá. Cuenta con la piscina de agua salada más grande de Centroamérica, toboganes, spa, casino y club nocturno.",
    images: ["https://picsum.photos/seed/playa-blanca-panama-1/800/600", "https://picsum.photos/seed/playa-blanca-panama-2/800/600", "https://picsum.photos/seed/playa-blanca-panama-3/800/600"],
    includes: ["Alojamiento todo incluido", "Acceso a piscina gigante de agua salada", "Toboganes", "Deportes acuáticos", "Club de niños", "Espectáculos nocturnos"],
    isVisible: true,
    departureDate: "2025-05-01",
    returnDate: "2025-05-05",
    country: "Panamá",
    city: "Playa Blanca",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Grupos"],
    amenities: ["Piscina", "Toboganes / Parque Acuático", "Acceso a la Playa", "Spa", "Casino", "Discoteca / Club Nocturno", "Shows Nocturnos / Animación", "Club de niños", "Restaurante", "Bar / Lounge", "Balcón / Terraza", "Cocineta", "Deportes Acuáticos", "Salón de Eventos / Conferencias", "Mesa de Tours"],
  },
  {
    id: 16,
    title: "Hotel Samawi",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 820000,
    durationDays: 4,
    description: "Ubicado en el sector Punta Hansa en San Andrés. Ofrece piscina al aire libre con vista al mar, wifi gratuito, salones para eventos y restaurante. Acepta mascotas.",
    images: ["https://picsum.photos/seed/samawi-1/800/600", "https://picsum.photos/seed/samawi-2/800/600", "https://picsum.photos/seed/samawi-3/800/600"],
    includes: ["Alojamiento con aire acondicionado", "Acceso a piscina con vista al mar", "Wifi gratuito"],
    isVisible: true,
    departureDate: "2025-02-20",
    returnDate: "2025-02-24",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Familias", "Negocios"],
    amenities: ["Piscina", "Cerca de la Playa", "Wifi Gratis", "Restaurante", "Bar / Lounge", "Salón de Eventos / Conferencias", "Se admiten mascotas", "Vista al Mar", "Minibar / Refrigerador"],
  },
  {
    id: 17,
    title: "Hotel Calypso",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 790000,
    durationDays: 4,
    description: "Hotel en San Andrés con una terraza en el noveno piso que alberga una piscina exterior, solárium y un restaurante con vistas al mar Caribe.",
    images: ["https://picsum.photos/seed/calypso-1/800/600", "https://picsum.photos/seed/calypso-2/800/600", "https://picsum.photos/seed/calypso-3/800/600"],
    includes: ["Alojamiento con aire acondicionado y minibar", "Acceso a piscina en la terraza"],
    isVisible: true,
    departureDate: "2025-03-10",
    returnDate: "2025-03-14",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Descanso / Relax"],
    amenities: ["Piscina", "Cerca de la Playa", "Restaurante", "Vista al Mar", "Aire Acondicionado", "Minibar / Refrigerador"],
  },
  {
    id: 18,
    title: "Hotel Ataraxy Boutique",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 700000,
    durationDays: 3,
    description: "Concepto contemporáneo que combina arte y calor de hogar en San Andrés. Ofrece wifi gratis y un trato personalizado. Nota: el hotel no cuenta con servicio de agua caliente.",
    images: ["https://picsum.photos/seed/ataraxy-1/800/600", "https://picsum.photos/seed/ataraxy-2/800/600", "https://picsum.photos/seed/ataraxy-3/800/600"],
    includes: ["Alojamiento climatizado", "Wifi gratis", "Amenidades para el aseo personal"],
    isVisible: true,
    departureDate: "2024-12-05",
    returnDate: "2024-12-08",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Cultural"],
    amenities: ["Cerca de la Playa", "Wifi Gratis", "Aire Acondicionado", "Restaurante", "Balcón / Terraza", "Minibar / Refrigerador"],
  },
  {
    id: 19,
    title: "Hotel On Vacation Blue Cove",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 900000,
    durationDays: 4,
    description: "Hotel en San Andrés con piscina panorámica, tres jacuzzis y río lento. Ideal para familias con zona Cove Kids exclusiva. Nota: baño privado con agua fría.",
    images: ["https://picsum.photos/seed/blue-cove-1/800/600", "https://picsum.photos/seed/blue-cove-2/800/600", "https://picsum.photos/seed/blue-cove-3/800/600"],
    includes: ["Alojamiento", "Acceso a piscina, jacuzzis y río lento", "Internet en áreas comunes", "Zona Cove Kids"],
    isVisible: true,
    departureDate: "2025-04-15",
    returnDate: "2025-04-19",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Piscina", "Piscina para niños", "Jacuzzi", "Río Lento", "Bar / Lounge", "Restaurante", "Wifi Gratis", "Aire Acondicionado", "Club de niños"],
  },
  {
    id: 20,
    title: "Hotel Portofino Caribe",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 720000,
    durationDays: 4,
    description: "Ubicado a una cuadra de la playa en San Andrés. Cuenta con piscina al aire libre, restaurante, bar y salón de eventos.",
    images: ["https://picsum.photos/seed/portofino-caribe-1/800/600", "https://picsum.photos/seed/portofino-caribe-2/800/600", "https://picsum.photos/seed/portofino-caribe-3/800/600"],
    includes: ["Alojamiento", "Acceso a piscina", "Internet inalámbrico"],
    isVisible: true,
    departureDate: "2025-05-10",
    returnDate: "2025-05-14",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Familias"],
    amenities: ["Piscina", "Cerca de la Playa", "Restaurante", "Bar / Lounge", "Salón de Eventos / Conferencias", "Wifi Gratis", "Aire Acondicionado", "Balcón / Terraza"],
  },
  {
    id: 21,
    title: "Hotel Dorado Plaza Bocagrande",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 980000,
    durationDays: 4,
    description: "Disfruta de un plan todo incluido a pocos pasos de la playa en Cartagena. Ofrece una amplia oferta gastronómica, bar en la piscina, animación en vivo, deportes acuáticos y espectáculos nocturnos.",
    images: ["https://picsum.photos/seed/dorado-plaza-1/800/600", "https://picsum.photos/seed/dorado-plaza-2/800/600", "https://picsum.photos/seed/dorado-plaza-3/800/600"],
    includes: ["Alojamiento todo incluido", "Comidas y bebidas", "Deportes acuáticos", "Entretenimiento y shows nocturnos"],
    isVisible: true,
    departureDate: "2025-06-01",
    returnDate: "2025-06-05",
    country: "Colombia",
    city: "Cartagena",
    regime: "Todo Incluido",
    travelerTypes: ["Grupos", "Familias", "Parejas"],
    amenities: ["Piscina", "Cerca de la Playa", "Shows Nocturnos / Animación", "Deportes Acuáticos", "Restaurante", "Bar / Lounge", "Wifi Gratis", "Aire Acondicionado", "Estacionamiento", "Hotel accesible"],
  },
  {
    id: 22,
    title: "Hotel Cartagena Dubai",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 510000,
    durationDays: 3,
    description: "Ubicado en el sector de Bocagrande, frente a las playas Costa del Sol. Cuenta con una piscina panorámica con vista al mar y wifi en toda la propiedad.",
    images: ["https://picsum.photos/seed/cartagena-dubai-1/800/600", "https://picsum.photos/seed/cartagena-dubai-2/800/600", "https://picsum.photos/seed/cartagena-dubai-3/800/600"],
    includes: ["Alojamiento con aire acondicionado", "Acceso a piscina panorámica", "Internet inalámbrico"],
    isVisible: true,
    departureDate: "2024-12-15",
    returnDate: "2024-12-18",
    country: "Colombia",
    city: "Cartagena",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Descanso / Relax"],
    amenities: ["Piscina", "Acceso a la Playa", "Vista al Mar", "Wifi Gratis", "Aire Acondicionado"],
  },
  {
    id: 23,
    title: "Hotel Yuldama Rodadero Inn",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 400000,
    durationDays: 3,
    description: "Ubicado a 300 metros de la playa El Rodadero en Santa Marta. Dispone de piscina, chapoteadero, estacionamiento y restaurante de especialidades caribeñas. Habitaciones con agua caliente.",
    images: ["https://picsum.photos/seed/yuldama-rodadero-1/800/600", "https://picsum.photos/seed/yuldama-rodadero-2/800/600", "https://picsum.photos/seed/yuldama-rodadero-3/800/600"],
    includes: ["Alojamiento con aire acondicionado", "Acceso a piscina", "Estacionamiento privado"],
    isVisible: true,
    departureDate: "2025-01-22",
    returnDate: "2025-01-25",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Grupos"],
    amenities: ["Piscina", "Piscina para niños", "Cerca de la Playa", "Estacionamiento", "Restaurante", "Aire Acondicionado", "Minibar / Refrigerador", "Agua Caliente", "Salón de Eventos / Conferencias"],
  },
  {
    id: 24,
    title: "Hotel Tucuraca by DOT",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 380000,
    durationDays: 3,
    description: "A 50 metros de la playa de El Rodadero en Santa Marta. Ofrece conexión Wi-Fi gratuita, servicio de desayuno y experiencias turísticas. Ideal para familias y parejas.",
    images: ["https://picsum.photos/seed/tucuraca-1/800/600", "https://picsum.photos/seed/tucuraca-2/800/600", "https://picsum.photos/seed/tucuraca-3/800/600"],
    includes: ["Alojamiento", "Conexión Wi-Fi gratuita", "Servicio de desayuno"],
    isVisible: true,
    departureDate: "2025-02-25",
    returnDate: "2025-02-28",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Con Desayuno Incluido",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Cerca de la Playa", "Wifi Gratis", "Mesa de Tours"],
  },
  {
    id: 25,
    title: "Hotel On Vacation Wayira Beach",
    category: "Cultural",
    price: "Consultar Precio",
    priceValue: 650000,
    durationDays: 3,
    description: "Una opción tranquila en Riohacha para estar en contacto con la naturaleza. Esta propiedad a pie de playa incorpora elementos de la cultura Wayúu en su decoración.",
    images: ["https://picsum.photos/seed/wayira-beach-1/800/600", "https://picsum.photos/seed/wayira-beach-2/800/600", "https://picsum.photos/seed/wayira-beach-3/800/600"],
    includes: ["Alojamiento con balcón", "Restaurante y bar", "Organización de tours (costo adicional)"],
    isVisible: true,
    departureDate: "2025-03-15",
    returnDate: "2025-03-18",
    country: "Colombia",
    city: "Riohacha",
    regime: "Solo Alojamiento",
    travelerTypes: ["Cultural", "Descanso / Relax", "Parejas"],
    amenities: ["Acceso a la Playa", "Restaurante", "Bar / Lounge", "Aire Acondicionado", "Balcón / Terraza", "Mesa de Tours"],
  },
  {
    id: 26,
    title: "ZiOne Luxury Hotel",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 680000,
    durationDays: 3,
    description: "En el sector de Bocagrande en Cartagena, a solo 100 metros de la playa. Se destaca su terraza con piscina y bar, además de salón de eventos y restaurante.",
    images: ["https://picsum.photos/seed/zione-luxury-1/800/600", "https://picsum.photos/seed/zione-luxury-2/800/600", "https://picsum.photos/seed/zione-luxury-3/800/600"],
    includes: ["Alojamiento de lujo", "Acceso a piscina en la terraza", "Wifi gratuito", "Estacionamiento"],
    isVisible: true,
    departureDate: "2025-04-20",
    returnDate: "2025-04-23",
    country: "Colombia",
    city: "Cartagena",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Negocios", "Descanso / Relax"],
    amenities: ["Piscina", "Cerca de la Playa", "Restaurante", "Bar / Lounge", "Salón de Eventos / Conferencias", "Wifi Gratis", "Aire Acondicionado", "Estacionamiento", "Minibar / Refrigerador"],
  },
  {
    id: 27,
    title: "Hotel BE La Sierra",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 430000,
    durationDays: 3,
    description: "Cerca de la playa El Rodadero en Santa Marta. Ofrece centro de negocios, salones de eventos, y restaurante de mariscos y comida internacional. Habitaciones con agua caliente.",
    images: ["https://picsum.photos/seed/be-la-sierra-1/800/600", "https://picsum.photos/seed/be-la-sierra-2/800/600", "https://picsum.photos/seed/be-la-sierra-3/800/600"],
    includes: ["Alojamiento con aire acondicionado", "Centro de negocios", "Internet inalámbrico gratuito"],
    isVisible: true,
    departureDate: "2025-05-15",
    returnDate: "2025-05-18",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Negocios", "Grupos"],
    amenities: ["Cerca de la Playa", "Centro de Negocios", "Salón de Eventos / Conferencias", "Wifi Gratis", "Aire Acondicionado", "Restaurante", "Minibar / Refrigerador", "Agua Caliente", "Mesa de Tours"],
  },
  {
    id: 28,
    title: "Hotel Blu by Tamaca",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 500000,
    durationDays: 3,
    description: "En El Rodadero, Santa Marta. Ofrece acceso a las instalaciones del Tamacá Beach Resort (a 80m), que incluyen acceso a playa, piscina, jacuzzi, gimnasio y salones de eventos.",
    images: ["https://picsum.photos/seed/blu-tamaca-1/800/600", "https://picsum.photos/seed/blu-tamaca-2/800/600", "https://picsum.photos/seed/blu-tamaca-3/800/600"],
    includes: ["Alojamiento", "Acceso a instalaciones de Tamacá Beach Resort", "Internet inalámbrico", "Estacionamiento"],
    isVisible: true,
    departureDate: "2025-06-10",
    returnDate: "2025-06-13",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Familias"],
    amenities: ["Piscina", "Jacuzzi", "Acceso a la Playa", "Gimnasio", "Salón de Eventos / Conferencias", "Wifi Gratis", "Aire Acondicionado", "Estacionamiento", "Minibar / Refrigerador", "Mesa de Tours"],
  },
  {
    id: 29,
    title: "Hotel La Riviera",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 460000,
    durationDays: 3,
    description: "En la fantástica zona de El Rodadero en Santa Marta, a pasos de la playa. Ofrece habitaciones con aire acondicionado, minibar y wifi gratis. Cuenta con centro de negocios.",
    images: ["https://picsum.photos/seed/la-riviera-1/800/600", "https://picsum.photos/seed/la-riviera-2/800/600", "https://picsum.photos/seed/la-riviera-3/800/600"],
    includes: ["Alojamiento con aire acondicionado", "Conexión a Internet wifi gratis", "Centro de negocios"],
    isVisible: true,
    departureDate: "2025-01-30",
    returnDate: "2025-02-02",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Grupos", "Negocios"],
    amenities: ["Cerca de la Playa", "Wifi Gratis", "Aire Acondicionado", "Minibar / Refrigerador", "Centro de Negocios"],
  },
  {
    id: 30,
    title: "Hotel Verde Mar",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 670000,
    durationDays: 4,
    description: "Ubicado en San Andrés, a 200 metros de la playa. Disfruta de la piscina exterior con servicio de bar, restaurante tipo bufet y la opción de rentar carros de golf.",
    images: ["https://picsum.photos/seed/verde-mar-1/800/600", "https://picsum.photos/seed/verde-mar-2/800/600", "https://picsum.photos/seed/verde-mar-3/800/600"],
    includes: ["Alojamiento", "Acceso a piscina", "Restaurante bufet"],
    isVisible: true,
    departureDate: "2025-03-28",
    returnDate: "2025-04-01",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Grupos"],
    amenities: ["Piscina", "Cerca de la Playa", "Restaurante", "Bar / Lounge", "Aire Acondicionado", "Minibar / Refrigerador", "Mesa de Tours"],
  },
  {
    id: 31,
    title: "Hotel Almirante",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 850000,
    durationDays: 4,
    description: "Moderno hotel a pasos de la playa de Bocagrande, Cartagena. Ofrece piscina, gimnasio con sauna, tres restaurantes, casino, y club de niños.",
    images: ["https://picsum.photos/seed/almirante-1/800/600", "https://picsum.photos/seed/almirante-2/800/600", "https://picsum.photos/seed/almirante-3/800/600"],
    includes: ["Alojamiento de lujo", "Acceso a piscina y gimnasio con sauna", "Club de niños", "Internet inalámbrico"],
    isVisible: true,
    departureDate: "2025-05-20",
    returnDate: "2025-05-24",
    country: "Colombia",
    city: "Cartagena",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Negocios", "Parejas"],
    amenities: ["Piscina", "Piscina para niños", "Acceso a la Playa", "Gimnasio", "Sauna", "Spa", "Club de niños", "Casino", "Restaurante", "Bar / Lounge", "Wifi Gratis", "Aire Acondicionado", "Estacionamiento", "Centro de Negocios", "Salón de Eventos / Conferencias"],
  },
  {
    id: 32,
    title: "Hotel Americas",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 650000,
    durationDays: 4,
    description: "A solo 2 cuadras de la playa principal de San Andrés. Ideal para familias o amigos, con piscina, restaurante y bar. Nota: las habitaciones no disponen de agua caliente.",
    images: ["https://picsum.photos/seed/americas-sai-1/800/600", "https://picsum.photos/seed/americas-sai-2/800/600", "https://picsum.photos/seed/americas-sai-3/800/600"],
    includes: ["Alojamiento con aire acondicionado", "Acceso a piscina", "Restaurante y bar"],
    isVisible: true,
    departureDate: "2025-06-15",
    returnDate: "2025-06-19",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Grupos"],
    amenities: ["Piscina", "Cerca de la Playa", "Restaurante", "Bar / Lounge", "Aire Acondicionado", "Minibar / Refrigerador"],
  },
  {
    id: 33,
    title: "Hotel Cartagena Premium",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 580000,
    durationDays: 3,
    description: "En la zona de Bocagrande, a 250 metros de la playa. Ofrece piscina exterior y jacuzzi en el piso 20 con vista panorámica, bar y restaurante.",
    images: ["https://picsum.photos/seed/cartagena-premium-1/800/600", "https://picsum.photos/seed/cartagena-premium-2/800/600", "https://picsum.photos/seed/cartagena-premium-3/800/600"],
    includes: ["Alojamiento con vista", "Acceso a piscina y jacuzzi en el piso 20", "Internet inalámbrico en recepción"],
    isVisible: true,
    departureDate: "2025-02-05",
    returnDate: "2025-02-08",
    country: "Colombia",
    city: "Cartagena",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Descanso / Relax"],
    amenities: ["Piscina", "Jacuzzi", "Cerca de la Playa", "Vista al Mar", "Bar / Lounge", "Restaurante", "Wifi Gratis", "Aire Acondicionado", "Minibar / Refrigerador"],
  },
  {
    id: 34,
    title: "Hotel Ocean View Cancun Arenas",
    category: "Internacional",
    price: "Consultar Precio",
    priceValue: 3100000,
    durationDays: 5,
    description: "Hotel de playa todo incluido en la Zona Hotelera de Cancún. Ideal para familias y viajeros de negocios, con tres piscinas, piscina para niños, y restaurante frente al mar.",
    images: ["https://picsum.photos/seed/ocean-view-cancun-1/800/600", "https://picsum.photos/seed/ocean-view-cancun-2/800/600", "https://picsum.photos/seed/ocean-view-cancun-3/800/600"],
    includes: ["Alojamiento todo incluido", "Comidas y bebidas", "Acceso a piscinas", "Actividades diurnas", "Wifi de alta velocidad gratis"],
    isVisible: true,
    departureDate: "2025-04-25",
    returnDate: "2025-04-30",
    country: "México",
    city: "Cancún",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Negocios", "Parejas"],
    amenities: ["Piscina", "Piscina para niños", "Acceso a la Playa", "Shows Nocturnos / Animación", "Restaurante", "Bar / Lounge", "Wifi Gratis", "Centro de Negocios", "Balcón / Terraza", "Cocineta"],
  },
  {
    id: 35,
    title: "Hotel Marco Polo Rodadero",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 390000,
    durationDays: 3,
    description: "En la zona turística de Rodadero, Santa Marta, a solo 2 cuadras de la playa. Sus habitaciones tienen un estilo moderno, aire acondicionado, TV y wifi.",
    images: ["https://picsum.photos/seed/marco-polo-rodadero-1/800/600", "https://picsum.photos/seed/marco-polo-rodadero-2/800/600", "https://picsum.photos/seed/marco-polo-rodadero-3/800/600"],
    includes: ["Alojamiento con aire acondicionado", "Wifi gratuito", "Balcón en algunas habitaciones"],
    isVisible: true,
    departureDate: "2025-03-01",
    returnDate: "2025-03-04",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Grupos"],
    amenities: ["Cerca de la Playa", "Wifi Gratis", "Aire Acondicionado", "Balcón / Terraza"],
  },
  {
    id: 36,
    title: "Hotel Occidental Caribe",
    category: "Internacional",
    price: "Consultar Precio",
    priceValue: 3800000,
    durationDays: 5,
    description: "Hotel todo incluido frente a la playa Arena Gorda en Bávaro, Punta Cana. Ofrece 798 habitaciones y suites, múltiples restaurantes, bares, piscinas y actividades.",
    images: ["https://picsum.photos/seed/occidental-caribe-1/800/600", "https://picsum.photos/seed/occidental-caribe-2/800/600", "https://picsum.photos/seed/occidental-caribe-3/800/600"],
    includes: ["Alojamiento todo incluido", "Comidas y bebidas", "Actividades diurnas y nocturnas", "Deportes acuáticos"],
    isVisible: true,
    departureDate: "2025-05-25",
    returnDate: "2025-05-30",
    country: "República Dominicana",
    city: "Punta Cana",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Parejas", "Grupos"],
    amenities: ["Piscina", "Acceso a la Playa", "Shows Nocturnos / Animación", "Deportes Acuáticos", "Restaurante", "Bar / Lounge", "Aire Acondicionado", "Balcón / Terraza", "Minibar / Refrigerador", "Hotel accesible"],
  },
  {
    id: 37,
    title: "Portobahia Hotel",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 410000,
    durationDays: 3,
    description: "Ubicado en Santa Marta, a unos metros de la playa El Rodadero. Las habitaciones están equipadas con TV por cable, wifi, minibar y aire acondicionado.",
    images: ["https://picsum.photos/seed/portobahia-1/800/600", "https://picsum.photos/seed/portobahia-2/800/600", "https://picsum.photos/seed/portobahia-3/800/600"],
    includes: ["Alojamiento con aire acondicionado", "Acceso a internet inalámbrico", "Caja de seguridad"],
    isVisible: true,
    departureDate: "2025-06-20",
    returnDate: "2025-06-23",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Grupos"],
    amenities: ["Cerca de la Playa", "Wifi Gratis", "Aire Acondicionado", "Minibar / Refrigerador"],
  },
  {
    id: 38,
    title: "Paquete Promocional Cancún",
    category: "Internacional",
    price: "$2,899,000 COP",
    priceValue: 2899000,
    durationDays: 5,
    description: "Cancún es una ciudad de México ubicada en la península de Yucatán que limita con el mar Caribe y que es conocida por sus playas, los numerosos centros turísticos y la vida nocturna.",
    images: ["https://picsum.photos/seed/promo-cancun-1/800/600", "https://picsum.photos/seed/promo-cancun-2/800/600", "https://picsum.photos/seed/promo-cancun-3/800/600"],
    includes: ["Tiquetes aéreos", "Alojamiento", "Tours básicos", "Vida nocturna"],
    isVisible: true,
    departureDate: "2025-04-05",
    returnDate: "2025-04-10",
    country: "México",
    city: "Cancún",
    regime: "Paquete Promocional",
    travelerTypes: ["Grupos", "Parejas"],
    amenities: ["Acceso a la Playa", "Shows Nocturnos / Animación", "Discoteca / Club Nocturno"],
  },
  {
    id: 39,
    title: "Paquete Promocional Cartagena",
    category: "Sol y Playa",
    price: "$899,000 COP",
    priceValue: 899000,
    durationDays: 4,
    description: "Cartagena es una ciudad que está ubicada a orillas del Mar Caribe. Sus calles coloridas llenas de encanto la hacen la puerta de entrada a Suramérica.",
    images: ["https://picsum.photos/seed/promo-cartagena-1/800/600", "https://picsum.photos/seed/promo-cartagena-2/800/600", "https://picsum.photos/seed/promo-cartagena-3/800/600"],
    includes: ["Transporte terrestre", "Alojamiento", "Desayunos", "Tour por la ciudad"],
    isVisible: true,
    departureDate: "2024-11-15",
    returnDate: "2024-11-19",
    country: "Colombia",
    city: "Cartagena",
    regime: "Paquete Promocional",
    travelerTypes: ["Familias", "Cultural", "Parejas"],
    amenities: ["Cerca de la Playa", "Cultural"],
  },
  {
    id: 40,
    title: "Paquete Promocional Santa Marta",
    category: "Sol y Playa",
    price: "$799,000 COP",
    priceValue: 799000,
    durationDays: 4,
    description: "Paisajes inolvidables donde el verde de su vegetación, sus montañas, el azul de sus mares y el contraste de las playas con el blanco de la Sierra Nevada, hacen de este paraíso un destino obligado.",
    images: ["https://picsum.photos/seed/promo-santa-marta-1/800/600", "https://picsum.photos/seed/promo-santa-marta-2/800/600", "https://picsum.photos/seed/promo-santa-marta-3/800/600"],
    includes: ["Transporte terrestre", "Alojamiento", "Desayunos", "Visita a playa"],
    isVisible: true,
    departureDate: "2024-10-25",
    returnDate: "2024-10-29",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Paquete Promocional",
    travelerTypes: ["Familias", "Descanso / Relax"],
    amenities: ["Cerca de la Playa", "Montaña"],
  },
];

export const DEFAULT_DESTINATIONS: Destination[] = [
  {
    id: 1,
    name: "San Andrés Isla",
    description: "Conocida por su mar de siete colores, es el destino perfecto para el buceo, el snorkel y relajarse en playas de arena blanca. Un paraíso en el Caribe colombiano.",
    image: "https://picsum.photos/seed/dest-sanandres/600/400",
  },
  {
    id: 2,
    name: "Santa Marta",
    description: "La magia de tenerlo todo. Disfruta de playas paradisíacas, la imponente Sierra Nevada y un centro histórico lleno de vida y color. La perla del Caribe te espera.",
    image: "https://picsum.photos/seed/dest-santamarta/600/400",
  },
  {
    id: 3,
    name: "Cartagena",
    description: "Sumérgete en el encanto de la ciudad amurallada, con sus calles coloniales, balcones floridos e historia vibrante. Un destino que enamora a cada paso.",
    image: "https://picsum.photos/seed/dest-cartagena/600/400",
  },
  {
    id: 4,
    name: "Eje Cafetero",
    description: "El corazón de la cultura cafetera de Colombia. Paisajes montañosos, pueblos coloridos y el aroma del mejor café del mundo te esperan en esta región única.",
    image: "https://picsum.photos/seed/dest-eje/600/400",
  },
  {
    id: 5,
    name: "Cancún y Punta Cana",
    description: "Vive el lujo del Caribe en su máxima expresión. Resorts todo incluido, playas de arena blanca, aguas turquesas y una infinidad de actividades para unas vacaciones perfectas.",
    image: "https://picsum.photos/seed/dest-internacional/600/400",
  },
  {
    id: 6,
    name: "Panamá",
    description: "Un destino de contrastes. Desde la modernidad de su capital y el icónico canal, hasta las playas vírgenes de sus costas. Panamá te sorprenderá.",
    image: "https://picsum.photos/seed/dest-panama/600/400",
  },
];


export const DEFAULT_TESTIMONIALS: Testimonial[] = [
    { id: 1, author: "Ana Pérez", text: "¡El viaje a San Andrés fue increíble! Todo estuvo perfectamente organizado. Gracias a Planifica Tu Sueño por hacer nuestras vacaciones inolvidables." },
    { id: 2, author: "Carlos Gómez", text: "Excelente servicio y atención al detalle. Nos ayudaron a personalizar nuestro tour por el Eje Cafetero y superó todas nuestras expectativas." },
    { id: 3, author: "Lucía Fernández", text: "La mejor agencia de viajes. Son profesionales, amables y siempre están dispuestos a ayudar. ¡Recomendadísimos!" },
];

export const DEFAULT_ABOUT_US_CONTENT: AboutUsContent = {
    mission: "Ser el portal profesional de salida (gateway) que facilita la materialización de los sueños de escape vacacional y ocio de la población en el Occidente de Caldas, ofreciendo una gestión de viajes organizada, vibrante y confiable.",
    vision: "Consolidar el liderazgo de reputación en nuestro mercado regional, manteniendo el alto nivel de satisfacción del cliente demostrado por nuestra calificación promedio de 4.9 estrellas sobre 5.0, y proyectar una imagen de marca dinámica, accesible y profesional.",
    foundations: [
        "Adherencia al régimen de responsabilidad establecido por la Ley 300/96 y normativas relacionadas.",
        "Operar como una Agencia de Viajes y Turismo clasificada como Prestadora de Servicios Turísticos (PST), con RNT 181495.",
        "El alto Capital Reputacional (4.9/5.0) y la integración en la economía social local.",
        "La identidad de 'Organización de Sueños' proyectada a través de una estética vibrante y soñadora."
    ],
    principles: [
        { title: "Legalidad", text: "El tratamiento debe sujetarse a la ley y las disposiciones que la desarrollen." },
        { title: "Finalidad", text: "El tratamiento debe obedecer a una finalidad legítima de acuerdo con la Constitución y la Ley." },
        { title: "Libertad", text: "El tratamiento solo puede ejercerse con el consentimiento previo, expreso e informado del titular." },
        { title: "Veracidad o Calidad", text: "La información debe ser veraz, completa, exacta, actualizada, comprobable y comprensible." },
        { title: "Transparencia", text: "Se debe garantizar el derecho del titular a obtener información acerca de la existencia de datos que le conciernan." },
        { title: "Acceso y Circulación Restringida", text: "El tratamiento se sujeta a los límites derivados de la naturaleza de los datos y solo podrá hacerse por personas autorizadas." },
        { title: "Seguridad", text: "La información se deberá manejar con las medidas necesarias para evitar su adulteración, pérdida, consulta o acceso no autorizado." },
        { title: "Confidencialidad", text: "Las personas que intervengan en el tratamiento de datos no públicos están obligadas a garantizar la reserva de la información." }
    ],
    values: [
        { title: "Confianza y Amabilidad", text: "Generada por nuestra alta reputación online y una atención cercana." },
        { title: "Profesionalismo y Seriedad", text: "Reflejado en nuestro conocimiento y atención al detalle." },
        { title: "Dinamismo y Entusiasmo", text: "Transmitido por nuestra energía y la pasión por lo que hacemos." },
        { title: "Organización", text: "Implícito en nuestro nombre, garantizando atención al detalle en la planificación." },
        { title: "Conocimiento Global", text: "Representando nuestra capacidad de ofrecer una amplia variedad de viajes." }
    ]
};

export const DEFAULT_LEGAL_CONTENT: LegalContent = {
    generalPolicy: `Planifica tu sueño está sujeta al régimen de responsabilidad que establece la ley 300/96, D.R. 1075/97, Decreto 2438 de 2010 y las normas que los modifiquen, adicionen o reformen. La responsabilidad del organizador del plan o paquete turístico se limita a los términos y condiciones del programa en relación con la prestación y calidad de los servicios. La agencia no asume ninguna responsabilidad frente al usuario por el servicio de transporte aéreo, salvo que se trate de vuelo fletado y de acuerdo con las condiciones del contrato de transporte. Las políticas de reembolso de los servicios no prestados en razón a situaciones de fuerza mayor o caso fortuito, acción u omisión de terceros o del pasajero, no atribuibles a la agencia de viajes, antes o durante el viaje, que puedan ser objeto de devolución, serán definidas por cada operador y las mismas serán confirmadas al usuario una vez se reserven y expidan los documentos de viaje, así como los porcentajes de penalidades o deducciones a que hubiere lugar. En caso de fuerza mayor o caso fortuito antes o durante el viaje (accidentes, huelgas, asonadas, terremotos, factores climáticos, condiciones de seguridad, etc.), o para garantizar el éxito del plan, el operador y/o la agencia podrán modificar, reemplazar o cancelar itinerarios, fechas, vuelos, hoteles, servicios opcionales, lo cual es desde ahora aceptado por el pasajero al momento de adquirir los servicios. El pasajero será el exclusivo responsable de la custodia de su equipaje y documentos de viaje.`,
    privacyPolicy: `Conscientes de la importancia que tiene la protección y el buen manejo de la información personal suministrada, LA AGENCIA DE VIAJES PLANIFICA TU SUEÑO ha diseñado la presente política para hacer un uso adecuado de sus datos personales, conforme a la Ley 1581 de 2012 y el Decreto 1377 de 2013. Su objetivo es garantizar la reserva de la información y la seguridad sobre el tratamiento que se le dará a la misma a todos los clientes, proveedores, empleados y terceros. El tratamiento de datos personales debe realizarse respetando las normas generales y especiales sobre la materia. Usted tiene derecho a conocer, actualizar, rectificar, consultar sus datos personales, solicitar prueba de la autorización otorgada, ser informado sobre el uso de sus datos, presentar quejas ante la Superintendencia de Industria y Comercio, revocar la autorización y/o solicitar la supresión de algún dato, y acceder en forma gratuita a sus datos personales.`
};

export const DEFAULT_FAQS: FAQItem[] = [
    { id: 1, category: "Legal y Operacional", question: "¿Cuál es la ubicación física y el teléfono de contacto?", answer: "Nuestra oficina está en el Centro Comercial La Colmena, Carrera 4 #13-32, Anserma, Caldas. Nuestro teléfono es 311 3653379." },
    { id: 2, category: "Legal y Operacional", question: "¿Cuál es el número del Registro Nacional de Turismo (RNT)?", answer: "Nuestro RNT es el 181495. Estamos clasificados como una Agencia de Viajes y Turismo (PST)." },
    { id: 3, category: "Políticas de Viaje", question: "¿Qué sucede si mi viaje se cancela por fuerza mayor?", answer: "En casos de fuerza mayor (clima, huelgas, etc.), para garantizar el éxito del plan, el operador o la agencia podrán modificar, reemplazar o cancelar itinerarios, fechas, vuelos y hoteles. Estas condiciones son aceptadas al adquirir los servicios." },
    { id: 4, category: "Políticas de Viaje", question: "¿En cuánto tiempo se procesan los reembolsos?", answer: "Los reembolsos, si aplican, se realizarán dentro de los 30 días calendario siguientes a la solicitud. El monto dependerá de las condiciones del proveedor y los gastos de administración." },
    { id: 5, category: "Políticas de Viaje", question: "¿La agencia se encarga del trámite de visas?", answer: "Brindamos la asesoría necesaria, pero el trámite, costos y la decisión final son de exclusiva autonomía de la autoridad consular. En caso de negativa de visa, no habrá lugar a reembolso." },
    { id: 6, category: "Datos Personales", question: "¿Cuáles son mis derechos sobre mis datos personales?", answer: "Usted tiene derecho a conocer, actualizar, rectificar, consultar y solicitar la supresión de sus datos personales, así como revocar la autorización para su tratamiento." },
    { id: 7, category: "Datos Personales", question: "¿Cómo puedo hacer una consulta o reclamo sobre mis datos?", answer: "Puede enviar sus solicitudes al correo electrónico planificatusueno12@gmail.com. Las consultas se atienden en máximo 10 días hábiles y los reclamos en 15 días hábiles." },
];