
import { Plan, Destination, Testimonial, AboutUsContent, LegalContent, FAQItem } from './types';

export const DEFAULT_LOGO_URL = 'https://lh3.googleusercontent.com/pw/AP1GczMVaa2t54xizfCT4x_LuthxbgVvbVait9QQs24AIFmmP11LvYGDQCc64rLNBOLySyjTMcywDRVWC5dm5Qlh5NNm9pOTJYkVQXX9XOHUlLIpOHbE4-5gZOdIICB1sueb_fejAJa5mRmHv-1PNAbqA-U=w991-h991-s-no-gm?authuser=0';
export const DEFAULT_PLANIBOT_AVATAR_URL = 'https://lh3.googleusercontent.com/pw/AP1GczN-20Rl_25uHFSXkszlbrLCBXowweXMKM6gxTaAT5SxEiJzHe6w1RzNl3uS9CDqypFK2VJwzZ0FJTKL2B9BsZwJg4yYjms8Xs6DGU6GvzMZ842bWpb6K9sot2XwqJdManGzs9soffeOFZjMlRm6COE=w991-h991-s-no-gm?authuser=0';
export const DEFAULT_SEO_IMAGE_URL = 'https://lh3.googleusercontent.com/pw/AP1GczMVaa2t54xizfCT4x_LuthxbgVvbVait9QQs24AIFmmP11LvYGDQCc64rLNBOLySyjTMcywDRVWC5dm5Qlh5NNm9pOTJYkVQXX9XOHUlLIpOHbE4-5gZOdIICB1sueb_fejAJa5mRmHv-1PNAbqA-U=w991-h991-s-no-gm?authuser=0';

export const REVIEW_IMAGE_URL = 'https://lh3.googleusercontent.com/pw/AP1GczN-20Rl_25uHFSXkszlbrLCBXowweXMKM6gxTaAT5SxEiJzHe6w1RzNl3uS9CDqypFK2VJwzZ0FJTKL2B9BsZwJg4yYjms8Xs6DGU6GvzMZ842bWpb6K9sot2XwqJdManGzs9soffeOFZjMlRm6COE=w991-h991-s-no-gm?authuser=0'; 

export const REVIEW_MESSAGE = "A Planifica Tu Sueño le encantaría recibir tus comentarios. Publica una opinión en nuestro perfil. https://g.page/r/CZJETIPfoLYKEBE/review y no olviden calificar con sus 5 estrellas";

export const DEFAULT_CONTACT_INFO = {
  phone: "+57 3113653379",
  whatsappLink: "https://wa.me/573113653379",
  email: "planificatusueno12@gmail.com",
  address: "Centro comercial La Colmena, Cra. 4 #13-32, Anserma, Caldas",
  schedule: "Lun-Vie: 8am-12pm y 2pm-5:30pm; Sáb: 8am-1pm",
  rnt: "181495",
};

export const DEFAULT_SOCIAL_LINKS = {
  facebook: "https://www.facebook.com/planifica.tusueno/",
  instagram: "https://www.instagram.com/planificatusueno/",
  tiktok: "https://www.tiktok.com/@planificatusueno",
  youtube: "https://www.youtube.com/@PlaniBot"
};

export const DEFAULT_CATEGORIES = [
    "Sol y Playa",
    "Rural",
    "Internacional",
    "Caribeño",
    "Aventura",
    "Cultural",
    "Romántico"
];

export const COMMON_AMENITIES = [
    "Piscina", "Jacuzzi", "Wifi Gratis", "Aire Acondicionado", 
    "Restaurante", "Bar / Lounge", "Estacionamiento", 
    "Gimnasio", "Spa", "Turco / Baño de vapor", 
    "Club de niños", "Acceso a la Playa", "Vista al Mar",
    "Minibar / Refrigerador", "Agua Caliente", "Mesa de Tours",
    "Salón de Eventos / Conferencias", "Hotel accesible",
    "Balcón / Terraza", "Se admiten mascotas"
];

export const COMMON_INCLUDES = [
    "Alojamiento", "Desayuno", "Almuerzo", "Cena", 
    "Snacks ilimitados", "Bebidas ilimitadas", 
    "Tiquetes Aéreos", "Transporte terrestre", 
    "Seguro de viaje", "Impuestos hoteleros",
    "Tours guiados", "Tarjeta de asistencia médica",
    "Traslado Aeropuerto-Hotel-Aeropuerto",
    "Bar abierto", "Shows nocturnos"
];

export const DEFAULT_TRAVEL_PLANS: Plan[] = [
  {
    id: 1,
    title: "Finca Hotel San Isidro",
    category: "Rural",
    price: "Consultar Precio",
    priceValue: 350000,
    durationDays: 2,
    description: "Dentro del alojamiento 🏨 podrá encontrar todas las comodidades: habitaciones equipadas con línea hotelera, Wifi, Piscina , Jacuzzy, Turco, senderos ecológicos, cascadas de nacimiento y muchas otras actividades que lo convierten en un lugar ideal para visitar y descansar.\n\nNuestra tarifa incluye alojamiento, alimentación, seguro de accidentes y la posibilidad de disfrutar de todas las amenidades que ofrece el hotel.\n\n• La tarifa incluye cena, desayuno y almuerzo del dia siguiente al ingreso. 🍲🥐☕🍳.\n• El check in al hotel es a las 3:00 pm y el check out a la 1:00 pm.\n• ⛅ La zona húmeda del hotel está en funcionamiento desde las 7:30 am hasta las 8:00 pm.\n• El horario de cierre de la zona social es a las 11:00 pm.\n• 🥛No se permitió el ingreso de bebidas ni comidas.\n• 🍻El hotel cuenta con cervezas nacionales e importadas, así como también algunos licores a precios competitivos.\n• 🏊🏻‍♀️El enfoque el hotel es el descanso por lo tanto no se permite la realización de fiestas.\n• Se recomienda llevar ropa cómoda 👕, traje de baño 🩳👙, bloqueador solar 🌞, cualquier tipo de medicamentos 💊 que pueda requerir en el tiempo de su estadía y zapatos cómodos 👟 .\n• No se permite el ingreso de mascotas.\n\nPrepárate para vivir una maravillosa experiencia.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipPiiWI8byu-k2v822Eoyj-Yf9XirsYlhzoGiSix=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipM0oastrBX9jlc5htbDQJPZb7ujgVUGg7f60IIj=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipM8Kpo53KGYF6YYW_CeQ9SSqnJfOg6W6DUTXTI0=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPLC900XKcREcroDsn467WB_7B7kHQrNPmJu-mJ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNS2pcyuZpHPaAi_94W0dc63u3ZsmHu_8Uyf2AK=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPCQFx25j4a7QxXDITbMl1DjCifSS24Ov4TnEBf=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNA4WZ-5zXaTsATL8TYbz_giPQnWLPCLsLuU7gS=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNZOkCbBM63SL29epsvH-WEzXtsibVO-bLZO47J=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOo2GeX5NFRwWsRpI7L_FymO3UDklFjgsL0zFbG=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNVlrPAcZ2rmJFUaweFRIpGkSrNmVDqiFAvdWMQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipN1fmF2nz9khyLu6vTtVi-Z95v1JZmR8qjwrrgy=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipO1XVZztAp58803GhLr7VhSTkw6nvxjls8oudcd=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipO3fmHAOr71qCb2L4qHCfCQWvQYekehOE7n0zea=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPJuyxBH71GnLpUG6u3hvfsjtZaA4mTRjDTQ5nx=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Cena, Desayuno y Almuerzo", "Seguro de accidentes", "Acceso a Piscina, Jacuzzi y Turco"],
    isVisible: true,
    isFeatured: true,
    departureDate: "2024-11-01",
    returnDate: "2024-11-02",
    country: "Colombia",
    city: "Rural",
    regime: "Pensión Completa",
    travelerTypes: ["Familias", "Descanso / Relax"],
    amenities: ["Piscina", "Jacuzzi", "Wifi Gratis", "Turco / Baño de vapor"],
    whatsappCatalogUrl: "https://wa.me/p/8576974672313200/573113653379"
  },
  {
    id: 2,
    title: "Hotel Sansiraka (Santa Marta)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 450000,
    durationDays: 3,
    description: "Acerca del Hotel\nSansiraka Hotel es una propiedad de estilo colonial con amplios jardines ubicada en la ciudad de Santa Marta, Colombia. El hotel está en la vía principal que lleva al centro turístico El Rodadero, el cual se ubica a 2 kilómetros de distancia.\n\nSansiraka Hotel cuenta con 59 habitaciones decoradas con estilo caribeño. Todas están equipadas con aire acondicionado, teléfono y baño privado con regadera.\n\nEntre sus instalaciones, Sansiraka Hotel tiene alberca al aire libre con mesa y sillas, jacuzzi y baño de vapor. Este hotel en Santa Marta también tiene un restaurante de comida regional e internacional, un bar con karaoke, una estación de agua y café en el lobby, hamacas y espectáculos nocturnos.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipO70W9g-24p9VL7hN-hFWKQPoQV1qfcU1_K-Rq0=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPt21i-i9PCXn8KAGmf493j7kqRyZMkqEjnLf_N=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOmCHDxh7sRuqZdvEr0e7iKg5kfbPzjY6m39DnU=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOATJo-O5AoYO7rrv7tk1aS3gKW_kCF1Kt2iNtG=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwM6u5nmrBtxgd-TU7qwKFq6iD874F5f7lI3HBLBoi95fJ2Znx_dyqqSMofSU9VGIEZ50JHzhPnIlBY8eHm9wHqnMcNA3RS6ufRDEP_zMosT-Z2u8yovWDB1hHU35PFA7W2Su7H=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwTM-Z3CmvR1jjaTF04dp5u8lTwm1vbBcXDldBhNovycGwgqKuYTHVqZzx7rBLcNhrczNxAbCvbFTkKj4OC2cWX1RnIh9Q93P9XlVuGRlkGegVAGBBNT1xeIXOgVJTKF8rzqcTH=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwAOCUEDZCOhdNLd1277mwtxolzIBhX9j2tLM7lLvnvtUN4em2oXx7Syiwu6j_xdbAWYzEoS1kiZmt8JqxlrfDzMgPXRi6Xz3ZkgXPk4qpVKYrQTSfmadk6RpAVLYz-QNHkUrzakQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwDzBUpElDui_kbR_eeCOrjE4eu_uBzlNma8Cx4KkdAcbzs-tPIqLsknzvVQaPW81rHuvqvEIsluPwna8ARoMHNnkxchwBkXj1rREUXoKXHzdNH8958i0aRCz4Paoc0vBPSDsn_wg=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyk7JNKkRwUpSTuP3beHIimSJ_GYe23gMfJv7NIFBwJMgIS0SD0TAH4GlqTRImJlp5DA6ukVg5L3wXwR-bssYAxzaWsHMqWVuEBbdHXTNfsZA42M8nV1O4rVUvFvOVOT8lasHk=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPN-r1MQP59H6oBHOg_HZ5ZSJjfrEUnSM751SZj=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Acceso a alberca y jacuzzi", "Baño de vapor", "Internet inalámbrico"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2024-11-15",
    returnDate: "2024-11-18",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Piscina", "Jacuzzi", "Aire Acondicionado", "Wifi Gratis", "Restaurante", "Bar / Lounge"],
    whatsappCatalogUrl: "https://wa.me/p/8204033959634780/573113653379"
  },
  {
    id: 3,
    title: "Hotel GHL Costa Azul (Santa Marta)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 550000,
    durationDays: 3,
    description: "Acerca del Hotel\nGHL Relax Costa Azul es un hotel de playa en Santa Marta, en la zona residencial de Pozos Colorados. El resort ofrece diversión para toda la familia y dispone de piscina, piscina para niños con juegos, jacuzzi y sauna. También brinda acceso a internet inalámbrico gratis y su restaurante invita a probar platos típicos locales.\n\nEl GHL Relax Hotel Costa Azul cuenta con bar en el área de la piscina rodeado de vegetación exótica, minisúper y mesa de tours.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipN9dF6AZPztxDUprwrHkjmJ4WJbrudpazLhLqb8=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNPHnUhjCxugths85OChaKYe73R1N7iIj4WdAP6=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzqUzgkTq0c7tRQXYI1uYWO4ySuwAXO2AyvBHLqiGczmCFTRffnXteKDjdwOGOUCxMCMdH6ckx05SXkA1vcEr9NmKSuPpGoH7qOpRwXH6AVaCLLr5Jh5IFQcPs_DOs6AB8-SOeMtw=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipODOTZweZM6_MUzi69zkzEWWXxm0cu4KdskdWU8=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNiK_-PxHDGtUPQU2AtDWSztAYUL1XA0ewfaYBQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzHg2fQExCDMAuoBNxw7kRHGii7dabFJobpNHT8l1F-rxNU3lFIIlrjczQ8CqScBWcvfJl3MV6OCeBaFKFqwlBJUKbhHbwv_BoRTfqJs_O--0TDzRyABWmyEtq8wffXvF3tlmoQbA=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzaoXZV5r252-VAX496vwuwSpQvi7JWiRJUH-3GiI-I0SJde6Omx5y6cXI0zVr6lgzefosijyNfLyXv8K4pcpZC3O7iUgpzPrXh1Gb7Ok--vOhJOnGMj7tsT0HKLzE4cotYc9Sj=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyIetbig1eBbLbp1efwjwGj1ad-u3eMBxCdzoKeUwI0uJFy0rG3zJVrV38Vt_rG-lYJb-6goS57P_i8ZwPynMznlXyniK5r7EZ3CTJ-WQF_p_dBlrjisRcyd_eAFiekYi86AEIF=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxOTWwncdPHh6TqKEKRTaZaQ2FTIFLOcYfqz4V2vqmYOM5YeeeD6VVTNZIhwY9syUjY13NZTai4vnTTTWTUhtRSNHVofn0Zg5H4UXowcEAh_ATYrjsQyfYN_vS-_OpCLeKNMK44dg=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzNpQEzxP1Cl_y4p9455eLY-VIa1oG2_xrTQDIr1T8FwAMYNkIzD1XoS1tqRMt1xCRv8wm8ePshkGPPJABnBQfI1l8_fevkTujMtDL__gZZe_QuQaHF08CGB_ZsqouNNTD7XJ9KaA=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Acceso a piscina y sauna", "Internet inalámbrico"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2024-12-01",
    returnDate: "2024-12-04",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Piscina", "Piscina para niños", "Jacuzzi", "Sauna", "Acceso a la Playa", "Wifi Gratis"],
    whatsappCatalogUrl: "https://wa.me/p/25810653308578122/573113653379"
  },
  {
    id: 4,
    title: "Grand Decameron Panama - All Inclusive",
    category: "Internacional",
    price: "Consultar Precio",
    priceValue: 3200000,
    durationDays: 5,
    description: "Royal Decameron Panamá - All Inclusive es un hotel todo incluido en el área de Playa Blanca en Farallón. Este complejo frente al mar tiene una amplia oferta recreativa para toda la familia, 11 piscinas, un nuevo tobogán con tres rampas de diferentes alturas, campo de golf de 18 hoyos y spa.\n\nAdemás, en el resort hay centro de convenciones, mesa de tours, numerosos bares, un club nocturno y hasta un carrito de raspados.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipNcxxLCEKm4eCis6G_qZgCIEGLWYNu_sDxn-EBe=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOuhc4urtufPb92Vel8UZ3h5JPJNzoMISW8qqx9=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNSr-KOO6xvCJ9a-1A2WEstuMspr8ryn3Ak-Dpz=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPPeMb4oZIxGqHwzrs2YUFVfvtfOpVxlllq4ALi=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPFgh9J4KLlyPa-HFf09PrCAQ9NtuwUui6eWWBI=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/KkZJHVEbwhLt_7t3KI6ktgi-muDL8HposfxZ8ppE00a6LC_SeQxh-9eetmkxOFxNclwLtAuxq5hPPhVTF39X_tWqvQXKG60AxDHI7MwgW-S-Xod2uR4nIX8rZHouuZzYtNG3p_tGd0RwM8y2Veqayns8qaNDIMo=s1360-w1360-h1020-rw"
    ],
    includes: ["Todo Incluido", "Comidas y bebidas ilimitadas", "Acceso a 11 piscinas", "Campo de golf (cargo extra)"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-01-10",
    returnDate: "2025-01-15",
    country: "Panamá",
    city: "Farallón",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Parejas", "Grupos"],
    amenities: ["Piscina", "Toboganes / Parque Acuático", "Campo de Golf", "Spa", "Discoteca / Club Nocturno", "Acceso a la Playa"],
    whatsappCatalogUrl: "https://wa.me/p/7093688827408212/573113653379"
  },
  {
    id: 5,
    title: "Hotel Marina Suites (Cartagena)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 480000,
    durationDays: 3,
    description: "Acerca del hotel\nHotel Marina Suites By Geh Suites tiene una ubicación ideal en el moderno sector de Bocagrande en Cartagena, a 2 cuadras del mar. La propiedad cuenta con acceso gratuito a internet inalámbrico, desayuno estilo americano y servicio de traslado al aeropuerto.\n\nEste hotel en Cartagena cuenta con una decoración moderna y estacionamiento. También ofrece paquetes para lunamieleros y tours.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipOZci1a_i1_jYH3tr8sfmAZ-rv9SOXnM4nl5PI=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipM7g2k57dD8zzk_E2jCAj0KNNFt6Pr5UZDhGCk=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMrsiujEvrDv-wZi9i_XYCwz7htu1ho75ef3-o=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOO9IqdZZMBIisZC3l53BS_0-ZCSveUKOuaxAM=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNLuqtspbgOSuxifyxfPXG_SHkqjD0qpbxMJwY=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Desayuno estilo americano", "Internet inalámbrico"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2024-11-20",
    returnDate: "2024-11-23",
    country: "Colombia",
    city: "Cartagena",
    regime: "Con Desayuno Incluido",
    travelerTypes: ["Parejas", "Negocios"],
    amenities: ["Wifi Gratis", "Aire Acondicionado", "Estacionamiento", "Centro de Negocios"],
    whatsappCatalogUrl: "https://wa.me/p/7229401933825410/573113653379"
  },
  {
    id: 6,
    title: "Hotel Grand Bavaro Princess Resort",
    category: "Internacional",
    price: "Consultar Precio",
    priceValue: 4500000,
    durationDays: 6,
    description: "Acerca del Hotel\nGrand Bávaro Princess All Suites Resort, Spa & Casino es un hotel todo incluido ubicado en Punta Cana, República Dominicana. Con su plan todo incluido se puede disfrutar de una gran variedad de actividades deportivas como snorkel, windsurf, kayak, catamarán, tiro al arco, tenis y clases de baile.\n\nEl complejo tiene gimnasio, dos piscinas, bañera de hidromasaje, sauna y zona ecológica con senderos entre manglares.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipOa_KOa336ytKWl6LrJF34YopSWdHPegD4jz7cd=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/I5JnoQkQ2n5_2bAv32_5pJWGiqRUnA70EcpGHDfn2vds4qNVGkA6FcWkSJoz7oe6IhQqQCxzLqH5UPV2t8tnbnmgFcOvTkwR-kcLOwqUqecpIjuuoFN_ap8mTX1W_gwSCdHh9kMej_1mWTt0e_sfQVAPN__12v8=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/CQ7ezs4v21RWpkIlTE1id3wzP-GbbMmk3fCk_-sNn62b4ZAmQ99HBu_G49VyO6rHRcRJ_kgaKljSoOFjfhEVQ30exA7SBtXO4qsjbH616JhlXvmdk0gGCafNuYzRMbdpx57Ao8havRzrx5RmQWaMfCK2UzKxI9c=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOBb3Mwxrql6tkJVeVNSeu7ZeaTgrRTXGPvUGhR=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/CXyX0wrCcRyJinis_Q-lvsrAhQXEwNovgV9yXu_nCHK99PHvLVNmSriTGxmzmLQp8CgKIvaiLBYDmsNCtLYFbi_XAfLbbRR7lBetwqX13_RPQASLwOyNiJrxsUt7TWlzOpqIQ9wDbyXq-gNjIqZzCukk5UfJfnE=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/VUfXkgUlTI2I9zhM4yp91hgUmobIR1F_25tjTEWKCegaemeFOz_vROIrbbGwodUg2nwUgl4J2XMeIwytbhQoOKN-K-eE4MsQ0la953nCSqKP5sL0Fy69x2WfWO_5YpJ-gi2997yQxa-dZ1KKkMrsnCQvLvx3lvk=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipP2qj21hFqOaXsHjGQvgfYmHghcvKhGfWtnnIIO=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/h2njmrs7jRyt0QxW4eaAOi2J9OOrgF3MKldbibNEztnvcsk5yedI5_QdQpaCv52twfP9MaXNM-VXTFIHu4ts2eU7JnuzOS7XZPntQyw0AGcvwzjnW8dKphJ-XKFZMe38R4Kymuf8W4pBolVfrI4lQ04osl6iAlw=s1360-w1360-h1020-rw"
    ],
    includes: ["Todo Incluido", "Actividades deportivas", "Acceso a gimnasio y piscinas", "Club de niños"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-02-10",
    returnDate: "2025-02-16",
    country: "República Dominicana",
    city: "Punta Cana",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Parejas", "Grupos"],
    amenities: ["Piscina", "Spa", "Casino", "Gimnasio", "Club de niños", "Wifi Gratis"],
    whatsappCatalogUrl: "https://wa.me/p/7889385907788367/573113653379"
  },
  {
    id: 7,
    title: "Hotel Imperial Las Perlas Todo Incluido",
    category: "Internacional",
    price: "Consultar Precio",
    priceValue: 2900000,
    durationDays: 5,
    description: "Este hotel familiar goza de una acertada ubicación a tan sólo 25 minutos en coche del aeropuerto internacional de Cancún y a 10 minutos de la principal zona comercial y de ocio nocturno.\n\nCon unas magníficas vistas del Mar Caribe, sus huéspedes podrán darse un refrescante chapuzón en la playa o simplemente desconectar sobre la blanca arena escuchando de fondo las suaves olas del mar.",
    images: [
        "https://lh3.googleusercontent.com/proxy/nTAZG78kvDj3rUcU4H20xr3fOFR9ppraudl-mlCgdP1wf1p0x9hi3PsQx5XhPgXlDPqoQ98u9Ml4oLzd_9YtBqdrmG4tH2BhPpe-YWXoQEQ6AbeLb_e0enmZYlsYbcC7EquUqLs6YjzcgyrUw3QRr6lQTcVa5Q=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/FpXmJuH9SsXgSGGkGvi9EAaXkVrtkBdZcc5V6HARA1snwmfU7tRtkxqyylkOrtFKTWrlKoVFh3VVMZPALJ8IqczIXGFjZC8NVfeMvls1TIlPbNWC5EggfbNnHHxNQt2qdTm0qIB_wCUYA1mImUcR1B7PgkaP_Q=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMKf8FEgQWRzv-VgJMrmCrWFD5cd0UL1e0H51oR=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/xmjTfraDlx_xGnJNAQPWDCCZSHNxnro3lcAK78YTpw8yDDK9HuV-zjBNv9h2mHzDRv5falJc-_3BRKI3ECKUFLJrNPXeXm8VTs7geCFwabULxaFuThYM6TcWPUs_1tO5gqphvDPfepNJQzfMZGC3RIcYAazTJA=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNH_ZoSLZKcWLQaLF5dRCxTC43_xvfcRF4s6eUM=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMckB0Q9WZ6VvDDYiN5IFLynvNmp51Nh3MYuhMO=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNGmiK2PMB4W2n2eUYSmSPN2emtUiy8a8pQWhVq=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPewUHL6yEIdskp4SJf6DaADeV8Afo1t5nzVse7=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento todo incluido", "Vistas al Mar Caribe", "Wifi de cortesía"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-03-05",
    returnDate: "2025-03-10",
    country: "México",
    city: "Cancún",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Piscina", "Acceso a la Playa", "Wifi Gratis", "Aire Acondicionado"],
    whatsappCatalogUrl: "https://wa.me/p/6867556923346658/573113653379"
  },
  {
    id: 8,
    title: "Hotel Azuan Suites (Cartagena)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 420000,
    durationDays: 3,
    description: "Acerca del Hotel\nHotel Azuan Suites By Geh Suites está ubicado en el moderno y turístico barrio de Bocagrande. Cuenta con servicio de transporte al aeropuerto, una cafetería, servicio de impresiones e información turística.\n\nLa propiedad tiene 33 habitaciones equipadas con wifi gratis, baño privado con ducha, aire acondicionado, televisión LCD, caja de seguridad, amenidades para el baño y servicio de despertador.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipMeidwlPLFWcYhYaHXcCMGBD9UYbH-OmfTz9z2J=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNXKb9tgpANVm3dBDErUS-qozVnN9rrZaQucc2U=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMeuhl9qQPqki3ZIwYpJwivGql8e_uddHGu9K7n=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNBTM65FmttjjBiY7b_FMwbjvzIUTwzfnmyaJ6z=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMDNewIHbu7Joyzo2G47rklROBcT5PmtIpl2gs-=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Wifi gratis", "Servicio de despertador"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2024-11-28",
    returnDate: "2024-12-01",
    country: "Colombia",
    city: "Cartagena",
    regime: "Solo Alojamiento",
    travelerTypes: ["Negocios", "Parejas"],
    amenities: ["Wifi Gratis", "Aire Acondicionado", "Ubicación privilegiada en Bocagrande"],
    whatsappCatalogUrl: "https://wa.me/p/7885221301559377/573113653379"
  },
  {
    id: 9,
    title: "Hotel Lord Pierre (San Andres)",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 780000,
    durationDays: 4,
    description: "Acerca del Hotel\nHotel Lord Pierre es una propiedad que cuenta con piscina y muelle con solárium, donde también se pueden realizar diversos eventos. Además tiene un área de playa.\n\nEl hotel ofrece una mesa de tours donde se pueden contratar diversas actividades acuáticas y en la ciudad. Posee un restaurante de comida caribeña e internacional, un restaurante de aperitivos y un bar ubicado sobre el muelle.",
    images: [
        "https://lh3.googleusercontent.com/proxy/Wa9d0dgkRj93lbbQw1IhN9-lZiNnzTzD4ovnI3e6z_Ujpi-PVpqymueLrs5gzePgaRPUpc4k-WQX_MZG15i-h8P7ADI1jz-h3XKY0tZ-DEmj87kpTv8KQkRRYPy_nKcJWEyihjkQjVUgr9zWhTT3D7DnYNDjUw=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/hq2ZLhZcBfYozw-vYyuOWpdExcBpGD9fWFNAmKoMQ7WCvnrxsejBi2sNCdoHLEK90lr2vhh9Mc7-IyfiMiKRMF_wD6DAHk-L489PhGMwEZAJPazTALthrZ-Pi3doYM_c_coqlVPo8aaHraQ_JeJu9anz9ulJCQY=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMRy6XtqJvNlrJTOVhgJBRx8NtuNdPdm2DZZqxk=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipP6UXW_eZcZhj9QJW1KK3DfduQL9KqiwJu4PvQy=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipP2qolWmIf7o4YFZEY-uPaRRGFpT3fkinvypmje=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNsZt54aDUz12_fThvP0HTJO8ywBLFgl33DzjAc=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Acceso a piscina y muelle", "Mesa de tours"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-01-05",
    returnDate: "2025-01-09",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Piscina", "Acceso a la Playa", "Wifi Gratis", "Restaurante", "Bar / Lounge"],
    whatsappCatalogUrl: "https://wa.me/p/7112269098876960/573113653379"
  },
  {
    id: 10,
    title: "Hotel On Vacation Caribbean",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 690000,
    durationDays: 4,
    description: "Acerca del Hotel\nOn Vacation Caribbean es un hotel cerca de la playa ubicado en la isla de San Andrés, Colombia. Es una propiedad libre de humo que ofrece 66 habitaciones con aire acondicionado, televisión con canales por cable, caja de seguridad y baño privado con ducha.",
    images: [
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwpYGrIK-vSEHZtWEcmV3w3hNhNabgFE-cL4v8euYSjElC8zAUWlmQoMMiE3ToKFkz1NCEXbAWebTrJzLhz0HoelM0Ohw-ASPlRUWN0zlr1oFSKo2q1kzasjCNMSwpsk30CTn6w=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSysUujEX7yfCl-ppFquIHEXjec-toolBqpYROxPX0ZKaIulciY4L1PNLx2mNtrq297YWseHOY09Ldh5dvo8VmFtGko-biqhWKSlhPrtADyDDUAkwrOmsYxhqUzg8fDM-Q2VlladmsEo7A=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPsZJKPgMN1T1nVWUl9-p8kWej6_E3Zxz2rj1bQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOeJ5JVglGKLL0wYPlGm_qhPENHv95qO400Cl2q=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPVBflQT5GsBFJcJatQO3NWqqUMyLALAzaqS34x=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMAIa9uzP7Im6TMqK81l6uN_-2NrkRmSHe7PsTw=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwvinx8D5-MpiAEF0uQvpnk45W1U0aCxj9qPdyrGcv8DD2MvdFHufCE07H2_vYua80ChSYo5x9VqGIxqW8pL0eYGa4Br7bXulzgN9Pqga0vxCBn-5p8LDEPn65F5ZyDzX8BkF7Yaw=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/kTWTvaWFcYG846IEwVL6VMTZny7eoX_VM6e4_lvgHBGbYI3w7k2U1OWfL_lPeVsOWipJVdpotvOGkEN0-iaOadCiC3csGSEZcONq-za4mEvpMNFZHU_eY_6_jOffZZSJwZ_9AqlOAI1YkIi-Wv2bDFCqiZG3MpM=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNNxzmiqlSn9btLiCe3H4e6lK8TGZp5aeOyqQTO=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Servicio de internet", "Restaurante"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-01-20",
    returnDate: "2025-01-24",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Familias"],
    amenities: ["Aire Acondicionado", "Wifi Gratis", "Restaurante"],
    whatsappCatalogUrl: "https://wa.me/p/25771297959150167/573113653379"
  },
  {
    id: 11,
    title: "Hotel Amazon (Leticia)",
    category: "Aventura",
    price: "Consultar Precio",
    priceValue: 1200000,
    durationDays: 4,
    description: "On Vacation Amazon está ubicado a las afueras de Leticia, en una zona a la que sólo se puede llegar en bote. Esta propiedad rodeada de selva está a 55 kilómetros del Parque Nacional Natural Amacayacu.\n\nEste hotel en el Amazonas cuenta con 50 habitaciones con vista a la selva. Todas están equipadas con aire acondicionado, televisión de pantalla plana y baño privado con regadera.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipP3IAHV9tt5fWxSBRuIUqH2mJIjVvoGEkkbeh7L=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipN4M8v19ZtY9-dgNj07Pd5jGUwokQKRm2_KuRxA=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPiRiCg5jwipkWahpaEGgq54aKMRlHJMr5GMPTH=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipO_NsDSKz51XY-XhVjjcR-T5MFry3qYvVsSCS2G=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyl7A0YwI02ubuJc07aog9vvzfbh_AWAXRwdQaRcpW4Qg5-dHlB6jrPP8ZhURbGi2yj8KEiff63YDaToTaqv9go8db0JzPtG_rL-mr9B03JgXqETJixpgXk85x4exJkwstwflt4=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMzfM1L6FJhFJbkmWhdtZkXAUD_mslLeDoU5ylJ=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Traslados en bote", "Acceso a piscina"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-04-10",
    returnDate: "2025-04-14",
    country: "Colombia",
    city: "Leticia",
    regime: "Pensión Completa",
    travelerTypes: ["Aventura", "Familias"],
    amenities: ["Piscina", "Restaurante", "Bar / Lounge"],
    whatsappCatalogUrl: "https://wa.me/p/8479613988720312/573113653379"
  },
  {
    id: 12,
    title: "Hotel Tamaca Beach Resort (Santa Marta)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 750000,
    durationDays: 3,
    description: "Tamacá Beach Resort Hotel es una propiedad ubicada frente al mar en el sector El Rodadero de Santa Marta, un área rodeada de una gran cantidad de restaurantes, bares y tiendas.\n\nEste hotel en Santa Marta tiene 82 habitaciones, contando con vista al mar. Las habitaciones se encuentran equipadas con aire acondicionado, baño privado con ducha, espejo de tocador, caja de seguridad, clóset y minibar.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipOQUzoCtcPe5Eyiy0ZFxaUDfc0YatTekTLtGrjk=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxh1LGhl73hIQxMKvrH_UYZ6_tBB7Mn8fQXV0gsX1FaoqRJ2BJxyDTpjQ9u44gHrc4LZw8BFKAOHhemZIY3zUNli0irZBgw3bsBX5NgC-YnVAizOTI0T4pxYvgbbs5vYhbVoutbgA=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMKVpHlW9hJuqORzPZPfJF67EqxHOI0_fnUI_TW=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMcxYxSk8vkEddyVYKuukssaYq5UhiKHOPW-BDH=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/mppVJ6T-xnyUlrL8Kebmxsp1XSbx8Y2DNjmnavcJem8Pbn9CIADcowTUiqCWQ72TzZ114IGl4xSoc50d7eG-pO6xtm7J4savnnMF213xHQnClqLqa8qE4ygUZvSq6wiU-GeHSrCcjZXrQxF0xdEjroSvJPBbtCM=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMa7uR101PgH9zb1jnH1gDwJY3wrXLRmL-yOEJ-=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipO0GMg3npBAVVl1ejNJtK_-B4z54HCrGYQMzX8U=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento con vista al mar", "Piscina con vista al mar", "Llamadas locales gratis"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-02-15",
    returnDate: "2025-02-18",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Piscina", "Acceso a la Playa", "Vista al Mar", "Wifi Gratis", "Aire Acondicionado"],
    whatsappCatalogUrl: "https://wa.me/p/7509111829143641/573113653379"
  },
  {
    id: 13,
    title: "Hotel Whala Bavaro (Punta Cana)",
    category: "Internacional",
    price: "Consultar Precio",
    priceValue: 3800000,
    durationDays: 5,
    description: "whala!bávaro es un hotel todo incluido cerca de la playa en Bávaro, Punta Cana. Para disfrutar de sus tres piscinas, dos restaurantes bufet y dos bares, además de gimnasio, club infantil y un programa completo de actividades y animación.",
    images: [
        "https://lh3.googleusercontent.com/proxy/5Y8hB2PMRHgM8n76dcK_L87ZKJG1J5qWW-oSl3MDcvHislfkBO99QPZO-dJSs7oeEDNyIq-ckdFQqLRpLd6k1yt9tt-QKaoeR91YnkpVnefSsbba1tbuNOorHLkofZLQ-zpzCQqoI96oDQNbzKiJU2W81Hd-4i4=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNUZb_usg5UVG3OUE2gP4yNTTybYIHXKt_gyOrR=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMObvf47gLVCjEPOCNrE5ISP5pEtAK05Y2EHR97=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipN4iSOeg3u0sEEVdfWQ-ONreWGhP33H6pNzKbLd=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/5Y8hB2PMRHgM8n76dcK_L87ZKJG1J5qWW-oSl3MDcvHislfkBO99QPZO-dJSs7oeEDNyIq-ckdFQqLRpLd6k1yt9tt-QKaoeR91YnkpVnefSsbba1tbuNOorHLkofZLQ-zpzCQqoI96oDQNbzKiJU2W81Hd-4i4=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPNcHQWOrz8cGt6Ii92txfing4IHWM-ykE85pQQ=s1360-w1360-h1020-rw"
    ],
    includes: ["Todo Incluido", "Actividades y animación", "Gimnasio", "Club infantil"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-03-20",
    returnDate: "2025-03-25",
    country: "República Dominicana",
    city: "Punta Cana",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Piscina", "Gimnasio", "Club de niños", "Restaurante", "Wifi Gratis"],
    whatsappCatalogUrl: "https://wa.me/p/7404863062900597/573113653379"
  },
  {
    id: 14,
    title: "Hotel Cartagena Plaza",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 850000,
    durationDays: 4,
    description: "Hotel Cartagena Plaza tiene una ubicación privilegiada frente al mar. La alberca, está situada en el piso 18, ofrece vistas panorámicas de Cartagena y del mar Caribe.\n\nDurante el día esta zona húmeda tiene música de ambiente y divertidas actividades; mientras que de noche el espacio se transforma para ser el escenario de espectáculos.",
    images: [
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyHBLy3iGtK8aK-ZI1RrdkDKHs-v-0EhKBt3ibMQccu28aMon52tHMuE0PvUqMUYov1hzJxbOmxtCeKQ5jVJ8JOvTYHxLvCR30c_VbBPWhe_63C1qAdqYHRKj3o89ewB6bVJHH7=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/86C0VIObQgwlhQfF0OHiWZ_NEDpGAuUNxe8TMW4tXLRXLsgZhRa0CLnKghJqm4wZs-xnha_KEU0q1Oxe852ZaFLuWrBJy8YFFB2W2PNNIxZu9225PJOTrjatr5IbVZ77d3ddenSmjvrhAFd7AcWOkWRRG8zZlIo=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/vM9FWh2yRAYH2BKSzXQSuXbtOXMzegRn_H7ar5YaSleJSg5cfMbpRxjpy0vYlDn6UgD8cGK6C2TxPdMIYjMKB79b2JNwagiN7AtOhmYsHbVjulXEX7omrnrFImTWLDiEBbpideXwVXdK8yhhNQG7txFtaZ4vVg=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/BoKmdxQF5a5Db13LK7kI1ksywEKj2BxIucf5oYFk_fB1iU_Wu3d4ERIB6KJHMIClIgUZfUW3z_xKKlanxBXE8kV0zPxv1CXRfoblHQHQ8jxl-roh9yFeqOnAkXVMysaT0qfFLJ6m3IQHh-yOecsDUY5j3qv39hQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/3zBqv87VuHBjKiv3I_RASIqhwCfGtYv4EYwsBF8jYUtOadTw5nh36ZRtbCQnGlcRl0YYW9yLuAko5NoxyH8_LHiqLppmGxlNTcAOm1L5tI_D7kmpJFGqYFuKX3IuFR0WDlwk9938V69u6riXiDYrAhB9n7S-OTQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwt3BleYgdPo5w412ItjjKPC2466xenpp7Uak8oRSYNzTHY5Uy3sQeMNne9EXq0DbF08YtAtAYo6FsRITnnjd_1lE6R7BZoaqtc3u8zPFRHL7aqxxE3EmGDYqBidKAFHabBP067=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/XyOaaVriAYhuxf-khjGjOLMlqUO4TjN7FgxOVn7JmdaxqFHVW-VQEw0H1x5LnUiR8Kxh561N8bTkeVg81iX1caOppAkZFIqQwTmiV3Zsq1APEzLqcAn7WgZEJfKoQbXyi43ANsxyRW-6lZa4dzaRq4C96N7tYas=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOwV9qs9_3cDthjtvqNWOU9w_8_EQJVhXDIbQoU=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Acceso a alberca piso 18", "Club de niños", "Música de ambiente"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-04-10",
    returnDate: "2025-04-14",
    country: "Colombia",
    city: "Cartagena",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Piscina", "Vista al Mar", "Club de niños", "Wifi Gratis", "Aire Acondicionado"],
    whatsappCatalogUrl: "https://wa.me/p/7724857634239573/573113653379"
  },
  {
    id: 15,
    title: "Hotel Playa Blanca Beach Resort",
    category: "Internacional",
    price: "Consultar Precio",
    priceValue: 3500000,
    durationDays: 5,
    description: "Playa Blanca Beach Resort es un hotel familiar de playa todo incluido ubicado en Playa Blanca, Panamá. Cuenta con la piscina de agua salada más grande de Centroamérica, exclusiva para huéspedes de las suites; toboganes, canchas de tenis y variedad de deportes acuáticos.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipOKDruDbqPdSTJkwFwuXi5hTxuD7jML2LRb-SGn=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwuUtGPpngublZzNLAAMazBfgjujin-WnV529Tn1nnMERBeggWpwj4HrHrgdY1f36fsG7ctYsqIx62KdeQX2lptJ_d3UkcZf3YB0uUSa3GSOIbCzDjbqfmqxdjC55OjAP4Wk1LO=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/vOdPjIzdOVM3t2O1qN0BH85RGsJde2J611qJoXJgjPZh0nVZ1UDv9G8Pw7OpZEmtjuPFxPbCO8DT4WaDO7vPdmazARQeST_QsObX1H4ANY7uSUJsD82xDI33A_GHPxpVHSQDBvhtWY2ZT5BoAqAWz8mHwEDYZQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPnoGrTgO6EhqbmD6gXM-MPoEgTNVj7PfWP13sr=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/uLS1ibzE-JtvP5ziLrsoosLx1aMUqXlFkIRz0MknvPTjTCeckJbwqrB6kYpArdDzrJ096al0bDiRWL-hfV7grjWfbAjn9oEC9gLpufbSTp2Iu4n9y4aZZl7691gFTmDVIKRuymQoF6CYtRfN0_8SUkuQOUE26Q=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMPzAx_LWYPmLFXhRATIKDC9e1rtOU2KMJ8Zqso=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/XUnteuCKC0qgyYAuSrGEIlsbWFeEvtHIOfBEZu1ZXa4v8KILahllzfuF6ygkm4JfvghD7413_mGbYDsQvSzONPFgf110QNyZ2CZCKquLlSilSp_FmmmZrIbRsHK5OnV5e3E7Qt79eOUQ195OAkBGS0hc1J-BzA=s1360-w1360-h1020-rw"
    ],
    includes: ["Todo Incluido", "Acceso a piscina gigante", "Toboganes", "Deportes acuáticos"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-05-10",
    returnDate: "2025-05-15",
    country: "Panamá",
    city: "Playa Blanca",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Grupos"],
    amenities: ["Piscina", "Toboganes / Parque Acuático", "Acceso a la Playa", "Wifi Gratis"],
    whatsappCatalogUrl: "https://wa.me/p/7887350717983893/573113653379"
  },
  {
    id: 16,
    title: "Hotel Samawi (San Andres)",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 950000,
    durationDays: 4,
    description: "Samawi Hotel se encuentra ubicado en el sector Punta Hansa en la Isla de San Andrés. Sus instalaciones ofrecen piscina al aire libre con vista al mar, acceso a wifi gratuito en todas las áreas, salones para eventos y servicio a la habitación.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipNMrFh_FHRO5eeqqodalDMgrOZQZtO-REH1CVa2=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPoTNx43EKowlVq2NUvICseFUhU-h_TSbbEOZ4r=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipODoKxlz52hKkkGL9fwFdRxZPZuuJwH4qFHcL8k=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOvRH6KS8rXWfkFrw9Q6fh1Drfy8Pcecbl9zY-a=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Acceso a piscina con vista", "Wifi gratis"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-06-01",
    returnDate: "2025-06-05",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Descanso / Relax"],
    amenities: ["Piscina", "Vista al Mar", "Wifi Gratis", "Restaurante", "Aire Acondicionado"],
    whatsappCatalogUrl: "https://wa.me/p/7422326524528538/573113653379"
  },
  {
    id: 17,
    title: "Hotel Calypso (San Andres)",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 880000,
    durationDays: 4,
    description: "Hotel Calypso San Andrés cuenta con una terraza en el noveno piso, en la cual hay una piscina exterior, solárium y un restaurante con vista al mar Caribe.\n\nLas habitaciones de la propiedad disponen de aire acondicionado, minibar y televisión con canales por cable.",
    images: [
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxGJeFwlTQL1SC9ukbuU9fReCBVfuO2xgiW4rpgZbQErVGG5DWycbTUertaS6fy6X-Ywvm0npjrGJbCsHaLr5kSWN61RjJnLAwshTcpghi2fx4Wr-UmeZi45Tva6LTpWJy_OHgn7H9KSYg=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSylHXx4Q9aIEsP-MRS_P-QkWt2YdKu2CW4T7_hykfNu4Fab-Bk7GND6mfxTrQDK1gLT-Pc424VxrbaFdr_Ag80iBgxGWCINfnXWLWEHrsLumNIEIzrqzBnReuhj0Cq1r9bTLPhEGA=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSz-ErEzZ995d5hok2mpheVYUvz4RzOlvIXuC8LZ1kadcbwPvv8lGjoolGqhrxK2R3j_0EmKgcLKT7Tzr56kC2xQ54T4161LoaKWBiHXvSXp4EeedGoqFcwRG6JXVo4FXmsgk_jYUA0QtTH6=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMEqdiMKcPma_MT0IElBhNEUU4kdN_6zN_ht187=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Acceso a piscina terraza", "Vistas al Mar Caribe"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-07-01",
    returnDate: "2025-07-05",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Familias"],
    amenities: ["Piscina", "Vista al Mar", "Restaurante", "Aire Acondicionado"],
    whatsappCatalogUrl: "https://wa.me/p/5924097514380724/573113653379"
  },
  {
    id: 18,
    title: "Hotel Ataraxy (San Andres)",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 720000,
    durationDays: 3,
    description: "Ataraxy Hotel Boutique ofrece un concepto contemporáneo que combina el arte con el calor de hogar y el trato personalizado. Este hotel en San Andrés ofrece wifi gratis.\n\nSus instalaciones incluyen un restaurante y terraza; además, tiene algunas habitaciones con comedor, área de descanso y jardín.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipN5imMZ_6842nX_sYWRJHSbGZrsAtCK0dnPeAyJ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/ZERIgvFmOdEokJ2L8SkzzUd4x6baITrb1Y_rGnX4S6D4hU-aeypHpVZR1qBhOMzZP-AJ5AJ8RY8o9qYqFgWHQtN_VVLKWYmawSQtCR3pTvDJTEQD1PUQZS07CDIxCGLvqim2SfDPnHlrVLC3WtkqTRg7lCtldwU=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMgjRCM1nBoImTOqgzyiPxJK5O-YHz8tZOB-MUc=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/vc6kOPttMkljxryIt4kfDp2sTDOb-QovtmLVxmTOvVVEMvNVFoQaI8WAPVGOcoSsmMlmmvvkRTsM-bKpDjbTXPwxcYY4AG2KjvZLtlBiKLEfsU0m2emx6evWnqqVrIEv_TYjUXdABj8ATrraQFdNcyrileAwOw=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento Boutique", "Wifi gratis", "Trato personalizado"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2024-12-10",
    returnDate: "2024-12-13",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Boutique"],
    amenities: ["Wifi Gratis", "Aire Acondicionado", "Restaurante"],
    whatsappCatalogUrl: "https://wa.me/p/7513996138681010/573113653379"
  },
  {
    id: 19,
    title: "Hotel Blue Cove (San Andres)",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 850000,
    durationDays: 4,
    description: "On Vacation Blue Cove tiene una piscina panorámica para adultos y otra para niños, tres jacuzzis y río lento.\n\nLas habitaciones disponen de televisión con canales por cable, aire acondicionado, baño privado con agua fría y caja de seguridad. Las habitaciones Cove Kids son ideales para familias con niños.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipN15dmY4yI2iXGp6oS-xyd4-JQmmP5oMNmHsxQT=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOBBNydr5jiJiqabHfrcIz6G-A7qda8py0ypbZ3=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMrqkJ4mHWTV5yYpLlCYWOmAXqeJz77iBsBlKjh=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyiIlgCqkGHDcMo_CHc1INZAlMFHLUhbrfgAnmigRxhY27ajsQtTKDiUNU0IvqxR3e-7N2-zuyJktbOU9-aQwFyySafrU-iXrLZFMw3t-eEC2qBjunb8hpCYdJWY0-TAezI0yfDjw=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNcKKQoYJXmgLfPQ__OAbf1QLYtBVk34wm_UX_W=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/ENbH9uVsLpVO7eOFuq9SIRKYKBMXsZHvtytegQjR7O6aZuJT134sJfdLhoks16Ydmm7eVQdugBKgguEYoIhLU8qMrEEc56UdttedwrK-I5xwKh8CvXBKV3HeIWh7hNyeGFAonBoK2JMblTa0Hmhf52tRI3eWA8I=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Acceso a piscina y jacuzzis", "Río lento"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-01-15",
    returnDate: "2025-01-19",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Piscina", "Jacuzzi", "Río Lento", "Club de niños", "Restaurante"],
    whatsappCatalogUrl: "https://wa.me/p/7606321736127095/573113653379"
  },
  {
    id: 20,
    title: "Hotel Portofino Caribe (San Andres)",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 710000,
    durationDays: 4,
    description: "Hotel Portofino Caribe se ubica en la isla de San Andrés, a una cuadra de la playa. Cuenta con piscina al aire libre, restaurante, bar, y salón de eventos. Ofrece servicio especial para lunamieleros; también tours a diferentes puntos turísticos de la zona.",
    images: [
        "https://lh3.googleusercontent.com/proxy/ouztaSk14Eemp0NiLt9aaAdnGGPR-qisdiaS8fGh_Tya_JkKElmWe6mgGqu831bXSKImvTvvKTOJd2psLq2m0g-Rkb6-9VkVhL0QQLj0SnLS1WQVyY2WB0z8vC7GAQDMwFNavegO08H5HavHNQxSGsI9h7agvA=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSy9rm05F_E9QGCfL3iAl48gEpsL5Qgb4eEseLR4gd97IOhir7e6gMbiKdBvF8ZctqeSJhl5K8o7voWO5-cvbT2uGjEs9IF_aBpCSeI--XprmjgO39EuXhuthq4SVRO0W6ov4xdCRQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/9cV7xX3NWpNQ6X9fdScrf0ZQjOWabKcdLVXJhJlhQmtLvsTuBR8OdLyDS0IEpc4r9hbjqcfG1McVsmpiofSSD7ogocDjmZfWTw31T8bDUPkDJQhJVL32DzAqmXQAIhErQYB2RUZz7uXudjJVwAtVpGTmPuKDW0s=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyR2m_rmSDC33_Dfy-eZdA2KA4o9qPfYPXuiUWgedmKdXY6RCeVyFJO8Ccue_wvQrx8vB-_iSPsSpjp4W_4CJk0peHzUipH3Q9PizACLLifiCIC5vxS71-74BwIRB_QcFulXvb9=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSx7UUrup2iQD1fE3M8q7mt_Q3OMahzvLkd5Qx2I5q_FPCd3FHekOwy4TiuPC70nKrfreCY9sGdU_DOBAGX6YXx3ZBFZy9JgMgDPF-Pr8EJzhlme2Hq_P1Luzp6QY1Rg0bscD8Q-=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Acceso a piscina", "Wifi Gratis"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-02-01",
    returnDate: "2025-02-05",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Piscina", "Wifi Gratis", "Restaurante", "Bar / Lounge"],
    whatsappCatalogUrl: "https://wa.me/p/7460126897390406/573113653379"
  },
  {
    id: 21,
    title: "Hotel Dorado Plaza (Cartagena)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 920000,
    durationDays: 4,
    description: "El Hotel Dorado Plaza Bocagrande Todo Incluido ofrece un espacio para aquellos que desean disfrutar de un plan todo incluido a pocos pasos de la playa y la bahía de Cartagena.\n\nEn el hotel puedes disfrutar de una amplia oferta gastronómica en sus dos restaurantes, un bar en la zona de la piscina que brinda bebidas con y sin alcohol, y noches temáticas.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipPr2i4VNdaR5n_R_qveeBBL0EZ-Vmd4W8UIbseQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/WQNzK1DQEWqddjjxSgTrpUVIhE45FU_3x3emRggOCH2rHiDVWBHyP6VJ_C9Q6Glv4bvn9vjV2wU97iiybfE8lXve8FwGOkXtqTdbLOCT1zutiDoPpSrqkCc5iDc3AH2imaBtxULFhwhaqej6EUXEQoZW0D_14g=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyQXHPuq9SSVcGhpsqO6n9y9Yqj7GnzXNVJLYzhz7J-nDQxRRR39J8NsTo6R0fUEuXiMsNwINf6ivrslmxG07hTnlDE8CcYdy3jKZWIMMSor0Kvv8JPNwes2KHpXZLuMGfMcURH4Q=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/_JB7RyBxW1DzunqVZu_mZ0O303N-8wvxi-1MDNN_x_fn7sDQ2YdBYq07NmWX9a78gLooAITt5dMbUjvci7XiXuf3VzD30ZWttAb3hFgr7ylPg4zJpjNU3XcVZ5jC_HWpUfJwB3EC2-gG_9BVr6Dd7R7y6kJbVg=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNV4NGf0K8VM6vI7tiLaCDAGFTXNxpwZSJSZKhW=s1360-w1360-h1020-rw"
    ],
    includes: ["Todo Incluido", "Comidas y bebidas", "Animación en vivo", "Deportes acuáticos"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-03-10",
    returnDate: "2025-03-14",
    country: "Colombia",
    city: "Cartagena",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Grupos", "Parejas"],
    amenities: ["Piscina", "Acceso a la Playa", "Wifi Gratis", "Restaurante", "Bar / Lounge"],
    whatsappCatalogUrl: "https://wa.me/p/7383694981697874/573113653379"
  },
  {
    id: 22,
    title: "Hotel Cartagena Dubai (Cartagena)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 550000,
    durationDays: 3,
    description: "Hotel Cartagena Dubai se encuentra en el sector de Bocagrande en la ciudad de Cartagena de Indias. Cuenta con una piscina panorámica con vista al mar.\n\nEl hotel está frente a las playas Costa del Sol y a 500 metros del Centro Comercial Bocagrande.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipOrGEY61cFw7l1mKjv0DXUqfSokxG3TUEd3Z24j=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/A0AOxET08VR6BRA1BPtLGIi6mGunnwMRT-NKURpylmSyjySBCfc0IrARm-qsdnoy8Q35dK2tacnDZXEA845QDJdkI-kpTvwalxbr8tAq0lM2xogIgBB_CNkOwZP-pVqwNuVXDdcWUKRyXVNkpaEok2gz8FEI7g=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/4gUBwnzqTWZI89lwX-VQvxRryrrRluCCFP2FtcZRbX3Y95i4--fxnSe_88GGBM20f-N1Ci5YNggw0y8OnlIPLSSSrZjrzgT9BkTwgigeEOvXg2w_Pq2G6iQD_7Sur1I3Y55maYFeddBu2nBwKbKeINcjLlMhLw=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzidr5WuBRog20w2dBPDkvhHc6ylJzLhqEsjNDWR7LO4NrfvvYipTnIZotmuGGeNrhAkUE09DTd4q47oAfdsOihHESYe5bySp851Vq3QsXW85rPYrtFQtH8tlcUmOQyeBnTBemy=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSx0dXezzJHpkwj55l1y4YxQRxRd6SDE2TWUGzTW0RC7gvA0L4HIs_NMTbaM6g6WzkGTF-Mkm48NfcGTuy8PtLnVwVgbDG9c4S0WjggU-I-YGew7COR4rh1ER19zNrvztOIfAuyP=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNEbHIit5EnncqHFpv3QPyfvEWYJn_kbc6pxh4y=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Piscina panorámica", "Wifi en toda la propiedad"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-04-05",
    returnDate: "2025-04-08",
    country: "Colombia",
    city: "Cartagena",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Descanso / Relax"],
    amenities: ["Piscina", "Vista al Mar", "Wifi Gratis", "Aire Acondicionado"],
    whatsappCatalogUrl: "https://wa.me/p/7455937991119942/573113653379"
  },
  {
    id: 23,
    title: "Hotel Yuldama Rodadero (Santa Marta)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 380000,
    durationDays: 3,
    description: "Hotel Yuldama Rodadero Inn es una propiedad ubicada a 300 metros de la playa en la zona de la popular playa El Rodadero, conocida por ser el punto más visitado de la ciudad.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipOqffil9xHLGp3dFVA5IXurTv0WyCIWqPH4mC_U=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipN6WGaeUeplmOSkd8n7qy76DKkEaToVXB5ZzlTy=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipME0nhSVaCfqMhfNRyKDjO8GbO6nk8QgtUEje8K=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPGVHmrmX7DCmuJiVsB9_9_PIF4o9gvM1LEdJW2=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPqDjC3PHyCs5YrcmfPHwH-CCU-7KHnm9tVdRB=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxTDCJHAzIfRkFG8rWBBv1sW0QGhc4F3Yl3twmCHoWy22Mm84fFsMRIOSYUuqupnut-xbmsSinb4nRXieJStwy5Z03_0CJGmoTQY_wTleLAdkR4r4YSiJJLsc7C_fc_5sL8woCK=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Acceso a piscina", "Estacionamiento privado"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-05-15",
    returnDate: "2025-05-18",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Piscina", "Estacionamiento", "Restaurante", "Aire Acondicionado"],
    whatsappCatalogUrl: "https://wa.me/p/25581331951480823/573113653379"
  },
  {
    id: 24,
    title: "Hotel Tucuraca By Dot (Santa Marta)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 360000,
    durationDays: 3,
    description: "Hotel Tucuraca by DOT Tradition se encuentra en Santa Marta, a 50 metros de la playa de El Rodadero y del Acuario y Museo del Rodadero.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipNpmowp14iWwXuVJ2o9R0jnBaCK6XaI41F6lBLY=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNHlkR8fYThRNWuRgJRq58OEDUjrKTazLeJO0Lz=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipN4plqySmSO_KVl5_TlSnW2CoXhzZFtR1mobBaa=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOWcjdw4iOpaA3i4hHhYoDK__LSljvegvsWeLaa=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Wifi gratuito", "Desayuno"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2024-12-05",
    returnDate: "2024-12-08",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Con Desayuno Incluido",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Wifi Gratis", "A pocos metros de la playa"],
    whatsappCatalogUrl: "https://wa.me/p/8139862502696823/573113653379"
  },
  {
    id: 25,
    title: "Hotel Wayira Beach (Riohacha)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 710000,
    durationDays: 3,
    description: "On Vacation Wayira Beach es una excelente opción para los viajeros que buscan un lugar tranquilo donde puedan estar en contacto con la naturaleza.",
    images: [
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwo4yeX2u22w8pX-BZGtGTrlONmsg2lFRF4gjU8BVyQ1utsknDFUH0POu4vXThlJGRtKtX9xq3WbC_0amsk1FcmXRIx8gJ101V-2fMTL8vTB2KV3GqfhGKGw0kMm-L1kfFI5S45CA=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSx_A-1gROoOrlinRntR1M9144tzj1ionl0WHI3QIR1Y6B0sMF6m8gBT19g5G3HBgCgF7-yLgjTApf_Hx_laT5XJunYiA_ioFym2RXRwMiSn7e24I7Sou7DIWXcadAQmpx4qfWz9=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/sCYGmgbiP1jnVSB3Fg5kTl3nOTKTgJKELA0EJ4EyJZOIrzWv0d_B2IFC_KUY0kgs4QZj5_lDYg1cEB2VCdEY1nDJWZgpBv3q4OVDfes-ePolErsYIhR4Rd_vVxtiEJpbzjWgWbabmhg220lV77vwdw-N8nMJXQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPyFTeILNYQSRLFR-my04gwcgT3IoSUS9sqNhdZ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipP5KwZTJMcuIKp0sPMsgSSfeoyMCn5zOu6z7-uQ=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento con balcón", "Contacto con la naturaleza", "Wifi Gratis"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-02-10",
    returnDate: "2025-02-13",
    country: "Colombia",
    city: "Riohacha",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Descanso / Relax"],
    amenities: ["Acceso a la Playa", "Restaurante", "Wifi Gratis", "Aire Acondicionado", "Balcón / Terraza"],
    whatsappCatalogUrl: "https://wa.me/p/7858083464225006/573113653379"
  },
  {
    id: 26,
    title: "ZiOne Luxury Hotel (Cartagena)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 680000,
    durationDays: 3,
    description: "ZiOne Luxury Hotel Cartagena se localiza en el sector de Bocagrande, a solo 100 metros de la playa. Destaca su terraza con piscina y bar.",
    images: [
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyukA028hNF_Yt_FpIHqgtxTlr6K9o2eS0njQXiNqdJjPamMH6qQ7Il7WhVvYzYevydRcbMkxwlpSNiAell70KwYdva4GiTQhj0emGka-oY4bymmgTJaw96H17cb98g3rcK3Lv0s8ky_Z0a=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNmWqmwXtuz5Dgp8QkKd48F0X1GGO3KgwkCV9CU=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzTgu43pJG91WFdL4wADbA8UbNkganCeE7DE9Cvd5OHK9n04SDUDxZxdJ713vE_0iaodYft-5Si7nNKUUkIg9IsNh9o4WOZzm2-Xm7yQ6BVYnnk-Hlz64vuxgtMDTLtn2g_BVJjPPYR7zIx=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipN5ArVqD6Ymz4QneBWDu3C79PoRGJKAb7TMh8jr=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNLL0KaE-DBGJZqFj7rGCVBThMa1x_n9YxpmdzZ=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento de Lujo", "Piscina en terraza", "Wifi Gratis"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-03-20",
    returnDate: "2025-03-23",
    country: "Colombia",
    city: "Cartagena",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Negocios"],
    amenities: ["Piscina", "Wifi Gratis", "Aire Acondicionado", "Restaurante", "Ubicación privilegiada en Bocagrande"],
    whatsappCatalogUrl: "https://wa.me/p/8088118457883772/573113653379"
  },
  {
    id: 27,
    title: "Hotel BE LA SIERRA (Santa Marta)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 420000,
    durationDays: 3,
    description: "Hotel BE La Sierra es una propiedad en la ciudad de Santa Marta que se encuentra cerca de la playa El Rodadero. Ideal para amantes del mar y la gastronomía.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipOsYAa3UtvuNDvTQow0e-Zp1LvNSTAevJivzW7W=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOn0ysAlj64liSEwpKXLbM6PnsC2OZZJm066NVL=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipM1LmvmP9EWV3rolooFkw0Ax6gDDbokXJHbgi6f=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNgXkd5GU7ZbZHdha9NjTsZbUIC62fjtoQ9ACRY=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Aire acondicionado", "Wifi en áreas comunes"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2024-12-15",
    returnDate: "2024-12-18",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Grupos"],
    amenities: ["A pocos metros de la playa", "Wifi Gratis", "Restaurante", "Aire Acondicionado"],
    whatsappCatalogUrl: "https://wa.me/p/7273466886035287/573113653379"
  },
  {
    id: 28,
    title: "Hotel Blue By Tamaca (Santa Marta)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 490000,
    durationDays: 3,
    description: "Blu Hotel by Tamaca está ubicado en the sector turístico de El Rodadero, en Santa Marta. Ofrece acceso a las instalaciones del Tamacá Beach Resort.",
    images: [
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzoSePqgp-ucMHaOLAr5ky5qzdoRELvnbXl87a7zllukdr5BgqABkfGomi0khLMtyB_HwnoBfZrGYACc1UvjE3XNjLXcdTA69d1WSjxRrmxaH7B888sKHGz-Pdxk1owOFT7euaf=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/RJHbGztgW-us_5c3Slr347vXdm8P75clGOczvRLpoc19-hHBmdiVC7yonUxd-zNxQdy29761eZmJ_KidLmd9NosaWt9Kypjxrt-KgCBjt-UhSN_uvYIWcDeH5JhueoO3vaNrbFwxCynNEbJ5psrFPcFLCW-_eeg=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/UddZcEHOUI4_91xpTg661X8MOUw4HZGN5-lI5QS3kRgowVc7KMqDH4OZBRIeEwMcVI3nSvAE7WepaWEgSnEFi1co90vWcHhc-tY4U33pAW9H-j8hmqz0vnLb6QT-1G86PTVLiZHRoZ1tiQEk04EvDPISLXPXF-E=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSybZjFz2drKVNtYm3lO_Y8RhntfPULOK2VxM6TbCk2mzIULN-NdBgO_EZri-hSpmik0qC48550-xs2d1xgV20jEJnfiqxFRT29APH7bFGEZ4SXsOUxboiwHdMEegY3vInIGSGiR=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzMlMeJFgZKCMqh72lOHQzsZKThrBakYy6dpmHobtvYXs6v6d3n5ryZ9EuERSEPgKlCK6g7nVj77tm67_WylTwuruM4zNRX5qtJn9V-lshEY0_N3j0cVvTza8YP4qvDyLODGrLO=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Acceso a instalaciones de Tamacá Beach", "Estacionamiento"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-01-10",
    returnDate: "2025-01-13",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Piscina", "Acceso a la Playa", "Wifi Gratis", "Estacionamiento"],
    whatsappCatalogUrl: "https://wa.me/p/7544537598968512/573113653379"
  },
  {
    id: 29,
    title: "Hotel La Riviera (Santa Marta)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 460000,
    durationDays: 3,
    description: "Si decides alojarte en Hotel La Riviera, te encontrarás en una fantástica zona de Santa Marta (El Rodadero) y estarás a menos de 1 min en coche de Playa El Rodadero.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipO9HIZos_sj_h4Q-ZvfapCq560-E0Wld6ANaOSV=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPIzLnqXgJovwE_5yOw7T1RqxtCoWf0xi2vmzZh=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipORKt6Crg8i6hb6k_Jy54gAqNeHpZYVJpcWBLgt=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Wifi gratis", "Centro de negocios"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-03-01",
    returnDate: "2025-03-04",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Negocios"],
    amenities: ["Wifi Gratis", "Aire Acondicionado", "A pocos metros de la playa"],
    whatsappCatalogUrl: "https://wa.me/p/25189981793981403/573113653379"
  },
  {
    id: 30,
    title: "Hotel Verde Mar (San Andres)",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 690000,
    durationDays: 4,
    description: "Hotel Verde Mar está ubicado en San Andrés, a 200 metros de la playa. Cuenta con alberca exterior donde se ofrece servicio de bar y restaurante bufet.",
    images: [
        "https://lh3.googleusercontent.com/proxy/ft6XNY47wPiTHBRVsG-TG_O8ZvLV4tYsXiVNgfzvGwWB-ff--mJNh7zs2iEVtcOWjKZueAyCyOfxUyu8dkSBORGXj9uOsICRR0jq8O2LILNWk1Xf7l27lls3WtKi5_9Wx8ZfgMs_RmMsKS4vZi7mr3gPlhawxQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPDkh8RPaFnrJeevsyatT7vcmMJUhSFW1-Q-kU6=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/gSXW4v5VIxkiwPQic0Fw1Hn97JrL-a_HVwd2-3BOAnVbOfXLshvwyneScC1kVjjwkouKtyQnUKqqlXazdcg3e0_LZM5OIYXCA_vcyDdh4JvRBzZ3p3B17qduLq0vp_HYACKnRsLUjSVWEw6mlHVmC4PL-FDE18Y=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipM9u4PEZ5NB-ejFygyXcPJvzBAfbA_QFaUPGKXE=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Acceso a piscina", "Servicio bufet"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-04-15",
    returnDate: "2025-04-19",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Grupos"],
    amenities: ["Piscina", "A pocos metros de la playa", "Restaurante", "Wifi Gratis"],
    whatsappCatalogUrl: "https://wa.me/p/7609488855776186/573113653379"
  },
  {
    id: 31,
    title: "Hotel Almirante (Cartagena)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 850000,
    durationDays: 4,
    description: "Este moderno hotel se ubica a unos pasos de la playa de Bocagrande. Cuenta con 250 habitaciones y una alberca con solárium, gimnasio con sauna y sala de masajes.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipP8bN7nQ32DPiskihHCb9gSnO_2ZVRuMoerAyz6=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPqrx2aUT_UedWHdQzbHfCZS_tGqrmeg52AuhU-=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOe3yyAmbDee7DmRudkmkJvzog5whZikNMgCxbs=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMYhwIruKpVeW5TQWSGL2W7OcaEJ3eC_ifPqTdV=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/Wa11fO__XGCdnt_rmYwHr8a6Yq2BqyQGbQXo-eBSNjTJJ4DJVWybMuU_xDQsSlWSfDJ7S3Ms9UD30vMWn4cgo8PAGXcQvEJa_jXLSw8MJXFy3DU5GSZoGS97KzeMXbmPxrL4ngOVavkdKihsd3qKNZ9qTwlxNQ=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Acceso a zonas húmedas", "Gimnasio", "Wifi de alta velocidad"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-05-20",
    returnDate: "2025-05-24",
    country: "Colombia",
    city: "Cartagena",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Parejas", "Negocios"],
    amenities: ["Piscina", "Gimnasio", "Spa", "Wifi Gratis", "Aire Acondicionado", "Acceso a la Playa"],
    whatsappCatalogUrl: "https://wa.me/p/7404742192906978/573113653379"
  },
  {
    id: 32,
    title: "Hotel Americas (San Andres)",
    category: "Caribeño",
    price: "Consultar Precio",
    priceValue: 650000,
    durationDays: 4,
    description: "Hotel Americas San Andres Islas se localiza a solo 2 cuadras de la playa principal. Es ideal para ir en familia o con amigos por su variedad de habitaciones.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipPMWkC0LmCycxA-zt88PUMTVCQ2xV9QvBnO_oOf=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/HCnpYbLV_MOQRNwZUawv0N8jseVp5xNzm2vwia6IpW0JIbunOUAc8yRqnF6XvaWsn4-WlqHHiCHeO_yqu8trcMAlw7GexcU-g8MUVLKZaSheOsb_vV9bkxuiC5nzjqwkhPRuIsJCqdaQo9B9j2lAlLUzEcruQQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNS1YWwr2AbrbZZFQYqhj_p0KMY4n8D2jussBWQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMykLMzrkdD4uBeTEagFysDkacF8YUmbvD5_BES=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Acceso a piscina", "Desayuno bufet"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-06-15",
    returnDate: "2025-06-19",
    country: "Colombia",
    city: "San Andrés",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Grupos"],
    amenities: ["Piscina", "Wifi Gratis", "Aire Acondicionado", "A pocos metros de la playa"],
    whatsappCatalogUrl: "https://wa.me/p/7419745838072516/573113653379"
  },
  {
    id: 33,
    title: "Hotel Cartagena Premium",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 580000,
    durationDays: 3,
    description: "Hotel Cartagena Premium se encuentra en la zona de Bocagrande. Cuenta con 140 habitaciones y una piscina exterior y jacuzzi en el piso 20 con vista panorámica.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipOrM3KZFXd-8MAz9oHUyvEF77JGColTy7ZrDRmz=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPbKBLLtcWb_ydhc_PUnJjZBE2wifPsV3JPEPQe=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzWiyLgUd4XakPLYxil_kFieSAnqh8rjRl7LQ88G9PPO5H8jR3yVuAV4rE5p8Lwf8v1gbOoNCoCBRIFBZM1Xz4AUbVuHJgX8NfXklwzsRMWqobx8FKUM9o4lrTnLBlLvSrlpwgI=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSybDfNbeITC7di-N-_1ZsEk36Wr6ccvEdGlhcXNy5YWxygODn8ThbxBX0K-GtPLF2IvYusicaE1kcbl2AwsVhtrLVZtL4-ruNkn6EgoRSo3kDH9byQE1k_uWN7vhyVq13RtG6x3UA=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Acceso a piscina panorámica", "Wifi Gratis"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-01-10",
    returnDate: "2025-01-13",
    country: "Colombia",
    city: "Cartagena",
    regime: "Solo Alojamiento",
    travelerTypes: ["Parejas", "Descanso / Relax"],
    amenities: ["Piscina", "Jacuzzi", "Vista al Mar", "Wifi Gratis", "Aire Acondicionado", "Ubicación privilegiada en Bocagrande"],
    whatsappCatalogUrl: "https://wa.me/p/7411013042347135/573113653379"
  },
  {
    id: 34,
    title: "Hotel Ocean View Cancun Arenas",
    category: "Internacional",
    price: "Consultar Precio",
    priceValue: 3100000,
    durationDays: 5,
    description: "Ocean View Cancún Arenas es un hotel de playa todo incluido en la Zone Hotelera de Cancún ideal tanto para familias como para viajeros de negocios.",
    images: [
        "https://lh3.googleusercontent.com/proxy/pJHoHnCfjAx6muYqUQr-m1kcj179ISjQz0w2bvMzaNBlCpdM_nEafJqidBDvAWsKWV_rTlpzhF_AF3G5VndrWwDIiEnJEt0qFp95sSmf_eDCOU4LgloHd7RETTgHQX-FA_sRKnGyku5uHerztzbetdEg0ivtLw=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/Lzbn-teCysw7MPKrnEuUlsEXoGw5jpA1qvyvfOwfNbyd6AYF2dFwstZ9NfHBULppk4Vjteql3rpjN5gGedJup8qAZf9Zyn2_RkweT6D9NQlmyzTcjrJ3wXxevHxXRRXTw6IDJm4OrOKEER1G6ATm_cBA-lptng=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/bX7n5NpQnljz4eC3ujua2C87KRpdAx02FQhYJMuN-SNL2WgGygFEo6R4MWc8RyQRiseapFG49-5yjolzlzTBi3czpEoLOR4BptIccSE4QGXRJwOwdFfZ189_Jcy7nh03ILOyO0nMO5DdvFE-oevE0_KivpvpSQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/r9rLQ8m5P9I5XBZLZIIWj5HUihANxl2CgKg5oDMxSdPzwU38Cv0atOp8XVO34IRMNHhdoo3UdlbfNyrPe1_X_RDdP6rYpO7DooLJ-TSoRUfHBB8MSMwZAD61iwml1lbX-SzHBpqo3lI_3mUnobafgbooZD3vhA=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwSYBtFOFy9AxJ2z_LQDuoe9Ra4Xouu0t7RtUgyB5OzEK97urxlxArUn-XSS658ysGS3AN1gs1C93kHBnL9zRltpapkfl09qPk4R3Cw23L_od4KOq_K6cwhumx5PM8q1Xg_huqY=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/4hNXP-32UV8EHWf3j1NRilhHKExH7px1nhz4akiPoCqkf7PeVbMlwJHNKnL5Sadu7Q0qaYKDnqByGm_VUQ8QvKd_WC_SZwnmr5s-acbLLwpZ0UJah0tarouRavbdETZfjqHjFs1zNiviWP2w5Tm1066InqtJJw=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPfvU5JOMgqzwl49t8LJSGryDkSP-UL7yNMAhzF=s1360-w1360-h1020-rw"
    ],
    includes: ["Todo Incluido", "Comidas y bebidas", "Acceso a 3 piscinas"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-04-20",
    returnDate: "2025-04-25",
    country: "México",
    city: "Cancún",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Negocios"],
    amenities: ["Piscina", "Acceso a la Playa", "Restaurante", "Wifi Gratis", "Aire Acondicionado"],
    whatsappCatalogUrl: "https://wa.me/p/7387565741330864/573113653379"
  },
  {
    id: 35,
    title: "Hotel Marco Polo (Santa Marta)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 390000,
    durationDays: 3,
    description: "Hotel Marco Polo Rodadero es un hotel in Santa Marta, in la zona turística de Rodadero, a solo 2 cuadras de la playa. Habitaciones modernas y balcón.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipPlIwnVxJq4NZEHYR8NcaKJotYCWWCPQvh8cYyu=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMLn5uS0p9K0zyI8I-SOH4lAael_qXVRfJG4g8A=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOUvHdkKYGT3t3gBJ39tr-i35u-pmQYvZRvq24W=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPiUE5JHYx_fogRS7i9_mL73Vab3EPwN2ptmNhD=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipNVaXPJlXxOPzQH3CcwEAbQXTLG0647vIRUXyIO=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Wifi Gratis", "Aire acondicionado"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-02-15",
    returnDate: "2025-02-18",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Wifi Gratis", "Aire Acondicionado", "A pocos metros de la playa"],
    whatsappCatalogUrl: "https://wa.me/p/7919680358045211/573113653379"
  },
  {
    id: 36,
    title: "Hotel Occidental Caribe (Punta Cana)",
    category: "Internacional",
    price: "Consultar Precio",
    priceValue: 3900000,
    durationDays: 5,
    description: "Occidental Caribe es un hotel todo incluido que se encuentra frente a la playa Arena Gorda en la zona de Bávaro. Habitaciones con balcón y minibar.",
    images: [
        "https://lh3.googleusercontent.com/p/AF1QipMZDa8NSVKKGnSYEuqPzZfIa3hkQwdN-wZEtLFa=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/VO5MwteaEWI7RCK-3EfOdNvSjzS44rcPYWTUJUCZPbwU_Nrk2OclB7FrZq_20-KZjK1IslGf6Yqema7OJiI0_NVUmvHALgFZwnfgKN0kzyvc7dUDe96_7hpV7h2Fcwi4WJPmb6C7RO609_Q9wWwuZ5LNGi8A1jU=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/Xt-Ki9uhYiEYhgzEh9UMEqcYPmG1_9e0t351G7due55DqeZ8wIBILzNP7erUeouhh-ozw0kX-TsrNnyvEgk9q-nD3qm_vf0jIeWYv482TuoVCQx8_nTsmDjp15f-rQuTCTGWkUOXTe98bDoE1klVwwccs7exSM0=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPKacri8mY8lKyFadpMYlRnUDSSGLvjEesmJ4cd=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/m9KbgbDlkBQ2plqZYisRaJPnUWPEPONiUYekMB4rP8D-zArFCO4o5Oq38oHFUPv2uiL9sgE_T4ADbPH8MsCfBfXzFG5B1mh6sRhm35F5kgro10FrCnHRqcpasIigXlia40l2UPMow3mKj0fwa7Tsfu95zxKZqQ=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/1b08VLEfHtofaiQY6cFO-_abuJyUItDnOSZbx0Wq8XgA11IT4YbxEA0Y_8O0JWDoLJHIEtQvlrE1hdWkXOPVuor4aTje7eqFBFx314DaVKV0lk5bXeDxjVtdUA37NBp3tZ0CsO2CrMPqoqfp16JFKtKWW4yUfg=s1360-w1360-h1020-rw"
    ],
    includes: ["Todo Incluido", "Minibar resurtido", "Vistas al Mar o Jardín"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-03-25",
    returnDate: "2025-03-30",
    country: "República Dominicana",
    city: "Punta Cana",
    regime: "Todo Incluido",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Piscina", "Acceso a la Playa", "Vista al Mar", "Restaurante", "Wifi Gratis"],
    whatsappCatalogUrl: "https://wa.me/p/7688559004497896/573113653379"
  },
  {
    id: 37,
    title: "Hotel Portobahia (Santa Marta)",
    category: "Sol y Playa",
    price: "Consultar Precio",
    priceValue: 400000,
    durationDays: 3,
    description: "Portobahia Hotel está ubicado in Santa Marta, a unos metros de la playa El Rodadero. Cuenta con 100 habitaciones equipadas con TV por cable y wifi.",
    images: [
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwg6JQk-0CkWUPH4RjeQfdRlIK7BC2xMifBq7e45dDfxTMszGuBipQi4yw2NeX6QMYCt7IGERXbDXQ2X9gP1B4ksFru-5NjqTgPNUxJuy_fJfMX_MSBD_fJCajdRXhggtix9JbxZHlKxN4Z=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/proxy/uXJxN_SR2pmS4vlp0zPJFiHugL58FbTwBYhLl9VF0oPAU95JGxadAiiRsG5ISePtdv2ZKSTO0M6pIsCWyD6HJClwVH6agjFhqKeTb4jl-AX1WEGyRLs_SVgSOCRtYizzTTF-x-hCxkeZ5com9o4Hc-sKg51QDA=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipN5Ad2k8BUcb02fraZHb8wU-sTgObOL6zUbsAi5=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipOMoL8h6rsNf8deZdBLUGMLj1WDbxLsVp6jqAJ6=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipMpTwRWA0aVo3tQeTDb6qW-IRFfI8kinoysiRlk=s1360-w1360-h1020-rw",
        "https://lh3.googleusercontent.com/p/AF1QipPKW1tHx-hZgZjHsW7yZOX91y4phl1I-2U8PKt1=s1360-w1360-h1020-rw"
    ],
    includes: ["Alojamiento", "Wifi Gratis", "Aire acondicionado"],
    isVisible: true,
    isFeatured: false,
    departureDate: "2025-01-05",
    returnDate: "2025-01-08",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Solo Alojamiento",
    travelerTypes: ["Familias", "Parejas"],
    amenities: ["Wifi Gratis", "Aire Acondicionado", "A pocos metros de la playa"],
    whatsappCatalogUrl: "https://wa.me/p/25358410607106462/573113653379"
  },
  {
    id: 38,
    title: "Paquete Promocional Cancún",
    category: "Internacional",
    price: "$2,899,000 COP",
    priceValue: 2899000,
    durationDays: 5,
    description: "🕌CANCUN🕌\n\nCancún es una ciudad de México ubicada in la península de Yucatán que limita con el mar Caribe y que es conocida por sus playas, los numerosos centros turísticos y la vida nocturna🏝️",
    images: [
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSztBDLIVFJS2aqq5feJbKtM1b7_b9MHophOONjU-kg6XnGRcQ8zf68gBbFTxpeyg-fE6ivuWzsd3ruErECTGcEl1vdwwEpMwDzsDVunCmtqvucJ0-n3Tn33-hSqDEVdYwF74yUA=w675-h390-n-k-no",
        "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcS2WztQ85paHU1jsQnui8QKrFCb7jvjzx6JwhHlADS42GPxFUQTpRFCspflAB00Np4TFf-AJ0P39Hbl2X06jioy4eg1&s=19",
        "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcS-WZjHb-mVyFsnekpAiEPBradpBx69wWa1FyWrXY0eLEUiztzcmFIGae4BAdrSdfoUV4fkBGpQ3ToRF9vjLpW5ess&s=19"
    ],
    includes: ["Tiquetes aéreos", "Alojamiento todo incluido", "Traslados"],
    isVisible: true,
    isFeatured: true,
    departureDate: "2025-05-01",
    returnDate: "2025-05-05",
    country: "México",
    city: "Cancún",
    regime: "Paquete Promocional",
    travelerTypes: ["Familias", "Grupos"],
    amenities: ["Piscina", "Acceso a la Playa", "Wifi Gratis", "Aire Acondicionado"],
    whatsappCatalogUrl: "https://wa.me/p/24034135376171829/573113653379"
  },
  {
    id: 39,
    title: "Paquete Promocional Cartagena",
    category: "Sol y Playa",
    price: "$899,000 COP",
    priceValue: 899000,
    durationDays: 4,
    description: "☀️CARTAGENA☀️\n\nCartagena es una ciudad que está ubicada a orillas del Mar Caribe. Sus calles coloridas llenas de encanto la hacen la puerta de entrada a Suramérica.🕌",
    images: [
        "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcS3MSAPvnQXTEV1zKo2vRkKHHNp5LlB95pm8eNmRVLS2RhWBEI9MpwWz0JbFIKjA3bgzBxddLEIQuHWjnbOybRIhok&s=19",
        "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQdItM4cf0JCQvUu4T6PpWEtC5iYeNJO_h-4NfBTINcrDHiWbWIePdMlfVIPimIUOlzUhYQrt88eKxvgjHQheSyeJ8&s=19",
        "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQc5c4xN5NfC-ExEHnrFwiBOPMA-AB-v7dInxwyOZSy0gvkfOTy-1_hlUj3tldCZaeeXsLZbUMuipOB_RK16F01zQ4&s=19",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSzLSKyxBOWSx3XPfVFsvWIA_aNDnsboOeqr6jtmVZIw4oSfqHWFNtW13TdyJuHReSUNNhe8ewWe0pK1dxQ0MgPPp0U7APN_V4UbBC_HN0m4zoh5G8lOiZCtzVSjfh1aXyabvLtyBQ=w675-h390-n-k-no",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwowOR-Mdb9Es71SkxfpHy6cbAotjGMqqVcPCSQhB3LmANwRbJVfEd7WvJzEK-vbyt_pXdy4-qpUJAxWU_A9PS7IvYbnp4UGYfiInZYwc3mY9oYcaKjCpisujya56JAR8okLGdeaA=w675-h390-n-k-no",
        "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQrINn2TqVM-XheKfhHCRa7HcbZJCS03pC3orXVpnO-KeCfn7RzEOOOIyHOfbwWYdB71VTcZMhHZfL1tSadTER7Wd0&s=19",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSz-iJ8qBgrebZiYqr07sDUHgP7oEZCY051VLiWHfKA0m61-AhLNZRgp8up8v242r7kljGZyd-aQYLLqLUS10EQPz3m8JZ_a34Wxp9O_qhtYddj4QrXR7r4e7SCpXBuIpryuhGNzig=w675-h390-n-k-no",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSxokkjszcbdA-LrK6ct55DwnPSVCrvKVH-F1mFy5-w0A3qSiLbBlIAVBiqKdiQGTxKK1Xi8BdYLp0fdt5MaiyryUe6bv9VbmYq9Ar__wAb_v6cxTi2h6NMCWhopKAP-tuuKpOi-=w675-h390-n-k-no",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwjuUqCyJ3XOBg76Wra5ircT6nVmrZethSsA7KWgJHiuDIuoCrTXskweXpjUVWan8sp4DhSc44QhyT5t7lz-FcCn4188lwjLGPJHI3NGUlguBQmCzAyg6TzOo5G3ruYfx6x5lQ=w675-h390-n-k-no"
    ],
    includes: ["Transporte terrestre", "Alojamiento", "Desayunos", "Tours"],
    isVisible: true,
    isFeatured: true,
    departureDate: "2025-06-10",
    returnDate: "2025-06-14",
    country: "Colombia",
    city: "Cartagena",
    regime: "Paquete Promocional",
    travelerTypes: ["Familias", "Cultural"],
    amenities: ["Wifi Gratis", "Aire Acondicionado", "A pocos metros de la playa"],
    whatsappCatalogUrl: "https://wa.me/p/6832493100122403/573113653379"
  },
  {
    id: 40,
    title: "Paquete Promocional Santa Marta",
    category: "Sol y Playa",
    price: "$799,000 COP",
    priceValue: 799000,
    durationDays: 4,
    description: "🌈SANTA MARTA🌈\n\nSu principal característica es su territorio: paisajes inolvidables in los que el verde de su vegetación, sus montañas, el azul de sus mares, el amarillo del sol y el contraste de las playas con el blanco de la Sierra Nevada.",
    images: [
        "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTKZOVcReCrEJ0vrUkqTkZNpj4a4iHUwxgqNQloE68m3oKHYpSNnOgnTPUxz8c3N4gbzbwgUO_-UBntbx0p7uohog8&s=19",
        "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcT2fjWAzpan3XMHEsrxqofGZfwzNgp_wBIJpBXvK_XfczKTFZBgEPRXbTIyYb0vtlReriYgRhRHFplkAIaXBPpsdMg&s=19",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwVH07F_etyRzJBbKGvb53MZPdg67g3E45NKTNwJTrDeiGq-i1C4LIN_IoCe1lLXLr76U_9jN-lcN55yNOaFbjXzgP4FiW07_Me_lDpyxoVvQgOK6fJAcX77oZhJUi5_vdWqLiO=w675-h390-n-k-no",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSz-SfaQfd0px2o-qfeC_ax39S1rECtwrQkbxNmrHQlMiUyo1dc-2yiDIP5x95CtAsAUNlh0kL_mop76MltKbDh20OnYpyrsA-TP5MzpWOwdO2BbleafTjuAPXfLT3NmGrA91mbc=w675-h390-n-k-no",
        "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTnTd4_G3nwu1QI2h8Bi256ECvJA_3NFStdSWYdsX5U8WqmY_Ml53cxRHXuZiydmPNZMk0kLLvVkZmhoU85T9BoogN7&s=19",
        "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcR2SdTL2K-aKOsbxaP2EIVDTL7A8gGvHz5XFPZruSZQwS2mbUphE0uI0Ko6lBWKtxxWPty8P2ujkXa9gEW2eLL32x9t&s=19",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwmShtdFzgn2zUwTF7Nu9baNAroDrhGIyZYfPJVowAcRqES0SZgSdSQxMit3_f_5LXmtoo-C_STCL88RPm_DWpmUP0d_cJ7Lo2bX3WpDugVlG4lYnJ3kkRbiyqBLR4eXtdLLA=w675-h390-n-k-no",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSy-7kj5gOFZ5f6h1s8uFM3MkWfn2rEhLUWpduqNQ3M4UnniA7pXP5R-VoM7TDXuisVCMh40FeBVMC8Rtz6CoQ4j9vFCla7PapV2AgitJXkm-0HTbEnLdANMhnTGJUhQouVc2dQUiQ=w675-h390-n-k-no",
        "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSwSR8KOc5gYE19YPKeKVisgmKqiHAx6hD8_MhX_4Y_0C8cTJDCJ1AW-RAuBAFY1pWGY3kcTCtrgeOccbcR0o-HfjKcIFrzZwPbOUTRSiLhwnaCAID_FEGQbeeuGLWL7bfLHcUJA=w675-h390-n-k-no",
        "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRspauFC8QnkIwWNVezyhOOl6ouIA7B3Slb07Eo57Tg5iDHKJL1VPkItKz6VxUst4Z7Pb3VFQDHTA8FO4mgGlKEvLI&s=19"
    ],
    includes: ["Transporte terrestre", "Alojamiento", "Desayunos", "Visitas a playas"],
    isVisible: true,
    isFeatured: true,
    departureDate: "2025-07-05",
    returnDate: "2025-07-09",
    country: "Colombia",
    city: "Santa Marta",
    regime: "Paquete Promocional",
    travelerTypes: ["Familias", "Descanso / Relax"],
    amenities: ["Wifi Gratis", "Aire Acondicionado", "A pocos metros de la playa"],
    whatsappCatalogUrl: "https://wa.me/p/6840570726002961/573113653379"
  }
];

export const DEFAULT_DESTINATIONS: Destination[] = [
    {
        id: 1,
        name: "San Andrés Isla",
        description: "El mar de los siete colores te espera. Disfruta de playas cristalinas, gastronomía isleña y la mejor rumba caribeña.",
        image: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTIiSxeewtn35vOo9zt6goz9ED1XkbVVmxSeaqfHExjKdvpqVMCI21ZEblyD0iGDghSnYbAwBkfrTUIAY7_ElFRUfg&s=19"
    },
    {
        id: 2,
        name: "Cartagena",
        description: "Historia, magia y encanto in la ciudad amurallada. Vive el romance y la cultura in cada esquina.",
        image: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQdItM4cf0JCQvUu4T6PpWEtC5iYeNJO_h-4NfBTINcrDHiWbWIePdMlfVIPimIUOlzUhYQrt88eKxvgjHQheSyeJ8&s=19"
    },
    {
        id: 3,
        name: "Santa Marta",
        description: "La magia de tener la Sierra Nevada y el mar Caribe juntos. Naturaleza, playas y aventura in un solo lugar.",
        image: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcTKZOVcReCrEJ0vrUkqTkZNpj4a4iHUwxgqNQloE68m3oKHYpSNnOgnTPUxz8c3N4gbzbwgUO_-UBntbx0p7uohog8&s=19"
    },
    {
        id: 4,
        name: "Eje Cafetero",
        description: "Paisajes verdes, aroma a café y la calidez de su gente. El destino ideal para descansar y conectar con la naturaleza.",
        image: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSynhxjVM1KK7hH4zkxqBFBvYNdvAdRsWqhk1ssR_TdZMUvUggm9a2NsPjmO4II3ESr0zXjFXThJnFJ_qkQIFabX8_bN4exRk9uK0ZQlH5kE5y55CTT0bawNZD2GkKzD8HcgO1nQ=w675-h390-n-k-no"
    },
    {
        id: 5,
        name: "Cancún",
        description: "Playas de arena blanca, aguas turquesas y una vida nocturna vibrante. El paraíso mexicano a tu alcance.",
        image: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcS-WZjHb-mVyFsnekpAiEPBradpBx69wWa1FyWrXY0eLEUiztzcmFIGae4BAdrSdfoUV4fkBGpQ3ToRF9vjLpW5ess&s=19"
    },
    {
        id: 6,
        name: "Punta Cana",
        description: "Lujo y relax in República Dominicana. Resorts todo incluido y playas interminables.",
        image: "https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcRAIkOYtLlYnanDPxYxedhwNhhNY2wntus2kxfqjdxTCQoczkpqPezs7WxV4jbEsiNF8_Vno4wT36pClwSdKVHFWkg&s=19"
    },
    {
        id: 7,
        name: "Panamá",
        description: "Descubre el Canal, la modernidad de la ciudad y la belleza de sus playas caribeñas in un solo viaje.",
        image: "https://lh3.googleusercontent.com/gps-cs-s/AG0ilSyQF7n12BTodERQgisLudHoJgIbo2CmrTvzrP-8PsPyLIetvNe2SyllRmcawGN_Z00o1Q51rJIYBvdwaQwDgwBlTU9xrs4UFnI3XJwKFAoFEk4P3F6qyHnM1rR3l2OfFm70_DeT=w675-h390-n-k-no"
    }
];

export const DEFAULT_TESTIMONIALS: Testimonial[] = [
    {
        id: 1,
        author: "María González",
        text: "¡La mejor experiencia de viaje! Todo estuvo perfectamente organizado, desde los vuelos hasta el hotel. Sin duda volveré a viajar con Planifica Tu Sueño.",
        rating: 5
    },
    {
        id: 2,
        author: "Carlos Rodríguez",
        text: "Excelente atención al cliente. Nos ayudaron a elegir el destino perfecto para nuestra luna de miel y superó nuestras expectativas.",
        rating: 5
    },
    {
        id: 3,
        author: "Ana López",
        text: "Viajamos in familia a San Andrés y fue inolvidable. El hotel recomendado fue ideal para los niños. ¡Gracias por todo!",
        rating: 4
    }
];

export const DEFAULT_ABOUT_US_CONTENT: AboutUsContent = {
    mission: "Nuestra misión es hacer realidad los sueños de viaje de nuestros clientes, ofreciendo experiencias únicas y personalizadas, con un servicio de alta calidad, responsabilidad y compromiso, superando siempre sus expectativas.",
    vision: "Ser reconocidos como la agencia de viajes líder in la región, preferida por la excelencia in el servicio, la innovación in nuestros productos turísticos y el compromiso con la satisfacción total de nuestros viajeros.",
    foundations: [
        "Experiencia y conocimiento del sector turístico.",
        "Alianzas estratégicas con los mejores proveedores.",
        "Tecnología al servicio del viajero.",
        "Equipo humano apasionado y comprometido."
    ],
    principles: [
        { title: "Calidad", text: "Buscamos la excelencia in cada detalle de nuestros servicios." },
        { title: "Seguridad", text: "Garantizamos el bienestar y la tranquilidad de nuestros clientes." }
    ],
    values: [
        { title: "Honestidad", text: "Actuamos con transparencia y rectitud in todas nuestras relaciones." },
        { title: "Responsabilidad", text: "Cumplimos nuestros compromisos y asumimos las consecuencias de nuestras acciones." },
        { title: "Pasión", text: "Amamos lo que hacemos y transmitimos esa energía in cada viaje." },
        { title: "Servicio", text: "Nuestra prioridad es la satisfacción del cliente." }
    ]
};

export const DEFAULT_LEGAL_CONTENT: LegalContent = {
    generalPolicy: "Planifica Tu Sueño se compromete a prestar servicios turísticos de calidad, cumpliendo con la normativa legal vigente. Nos reservamos el derecho de admisión y permanencia. Las tarifas están sujetas a cambios sin previo aviso y disponibilidad.",
    privacyPolicy: "En Planifica Tu Sueño respetamos su privacidad. Sus datos personales serán tratados conforme a la Ley de Protección de Datos Personales. La información recolectada se utilizará exclusivamente para la prestación de los servicios contratados y el envío de información promocional, si así lo autoriza."
};

export const DEFAULT_FAQS: FAQItem[] = [
    {
        id: 1,
        question: "¿Cuáles son los métodos de pago?",
        answer: "Aceptamos efectivo, transferencias bancarias, tarjetas de débito y crédito. También ofrecemos planes de financiación.",
        category: "Pagos"
    },
    {
        id: 2,
        question: "¿Qué incluye el plan todo incluido?",
        answer: "Generalmente incluye alojamiento, todas las comidas, bebidas ilimitadas, actividades recreativas y, in algunos casos, transporte y tours. Verifica los detalles específicos de cada plan.",
        category: "Servicios"
    },
    {
        id: 3,
        question: "¿Puedo cancelar mi reserva?",
        answer: "Sí, las políticas de cancelación varían según el proveedor y la tarifa contratada. Te recomendamos revisar las condiciones antes de reservar.",
        category: "Reservas"
    },
    {
        id: 4,
        question: "¿Necesito visa para viajar?",
        answer: "Depende del destino y tu nacionalidad. Nosotros te asesoramos sobre los requisitos migratorios para tu viaje.",
        category: "Documentación"
    },
    {
        id: 5,
        question: "¿Ofrecen seguros de viaje?",
        answer: "Sí, todos nuestros planes incluyen o pueden incluir tarjeta de asistencia médica para que viajes tranquilo.",
        category: "Seguridad"
    }
];
